# coding: utf-8

"""
    TVDB API V4

    Documentation of the TVDB API V4  # noqa: E501

    The version of the OpenAPI document: 4.3.0
    Generated by: https://openapi-generator.tech
"""


import inspect
import pprint
import re  # noqa: F401
import six

from openapi_client.configuration import Configuration


class ArtworkExtendedRecord(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'episode_id': 'int',
        'height': 'int',
        'id': 'int',
        'image': 'str',
        'language': 'str',
        'movie_id': 'int',
        'network_id': 'int',
        'people_id': 'int',
        'score': 'float',
        'season_id': 'int',
        'series_id': 'int',
        'series_people_id': 'int',
        'thumbnail': 'str',
        'thumbnail_height': 'int',
        'thumbnail_width': 'int',
        'type': 'int',
        'updated_at': 'int',
        'width': 'int'
    }

    attribute_map = {
        'episode_id': 'episodeId',
        'height': 'height',
        'id': 'id',
        'image': 'image',
        'language': 'language',
        'movie_id': 'movieId',
        'network_id': 'networkId',
        'people_id': 'peopleId',
        'score': 'score',
        'season_id': 'seasonId',
        'series_id': 'seriesId',
        'series_people_id': 'seriesPeopleId',
        'thumbnail': 'thumbnail',
        'thumbnail_height': 'thumbnailHeight',
        'thumbnail_width': 'thumbnailWidth',
        'type': 'type',
        'updated_at': 'updatedAt',
        'width': 'width'
    }

    def __init__(self, episode_id=None, height=None, id=None, image=None, language=None, movie_id=None, network_id=None, people_id=None, score=None, season_id=None, series_id=None, series_people_id=None, thumbnail=None, thumbnail_height=None, thumbnail_width=None, type=None, updated_at=None, width=None, local_vars_configuration=None):  # noqa: E501
        """ArtworkExtendedRecord - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._episode_id = None
        self._height = None
        self._id = None
        self._image = None
        self._language = None
        self._movie_id = None
        self._network_id = None
        self._people_id = None
        self._score = None
        self._season_id = None
        self._series_id = None
        self._series_people_id = None
        self._thumbnail = None
        self._thumbnail_height = None
        self._thumbnail_width = None
        self._type = None
        self._updated_at = None
        self._width = None
        self.discriminator = None

        if episode_id is not None:
            self.episode_id = episode_id
        if height is not None:
            self.height = height
        if id is not None:
            self.id = id
        if image is not None:
            self.image = image
        if language is not None:
            self.language = language
        if movie_id is not None:
            self.movie_id = movie_id
        if network_id is not None:
            self.network_id = network_id
        if people_id is not None:
            self.people_id = people_id
        if score is not None:
            self.score = score
        if season_id is not None:
            self.season_id = season_id
        if series_id is not None:
            self.series_id = series_id
        if series_people_id is not None:
            self.series_people_id = series_people_id
        if thumbnail is not None:
            self.thumbnail = thumbnail
        if thumbnail_height is not None:
            self.thumbnail_height = thumbnail_height
        if thumbnail_width is not None:
            self.thumbnail_width = thumbnail_width
        if type is not None:
            self.type = type
        if updated_at is not None:
            self.updated_at = updated_at
        if width is not None:
            self.width = width

    @property
    def episode_id(self):
        """Gets the episode_id of this ArtworkExtendedRecord.  # noqa: E501


        :return: The episode_id of this ArtworkExtendedRecord.  # noqa: E501
        :rtype: int
        """
        return self._episode_id

    @episode_id.setter
    def episode_id(self, episode_id):
        """Sets the episode_id of this ArtworkExtendedRecord.


        :param episode_id: The episode_id of this ArtworkExtendedRecord.  # noqa: E501
        :type episode_id: int
        """

        self._episode_id = episode_id

    @property
    def height(self):
        """Gets the height of this ArtworkExtendedRecord.  # noqa: E501


        :return: The height of this ArtworkExtendedRecord.  # noqa: E501
        :rtype: int
        """
        return self._height

    @height.setter
    def height(self, height):
        """Sets the height of this ArtworkExtendedRecord.


        :param height: The height of this ArtworkExtendedRecord.  # noqa: E501
        :type height: int
        """

        self._height = height

    @property
    def id(self):
        """Gets the id of this ArtworkExtendedRecord.  # noqa: E501


        :return: The id of this ArtworkExtendedRecord.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ArtworkExtendedRecord.


        :param id: The id of this ArtworkExtendedRecord.  # noqa: E501
        :type id: int
        """

        self._id = id

    @property
    def image(self):
        """Gets the image of this ArtworkExtendedRecord.  # noqa: E501


        :return: The image of this ArtworkExtendedRecord.  # noqa: E501
        :rtype: str
        """
        return self._image

    @image.setter
    def image(self, image):
        """Sets the image of this ArtworkExtendedRecord.


        :param image: The image of this ArtworkExtendedRecord.  # noqa: E501
        :type image: str
        """

        self._image = image

    @property
    def language(self):
        """Gets the language of this ArtworkExtendedRecord.  # noqa: E501


        :return: The language of this ArtworkExtendedRecord.  # noqa: E501
        :rtype: str
        """
        return self._language

    @language.setter
    def language(self, language):
        """Sets the language of this ArtworkExtendedRecord.


        :param language: The language of this ArtworkExtendedRecord.  # noqa: E501
        :type language: str
        """

        self._language = language

    @property
    def movie_id(self):
        """Gets the movie_id of this ArtworkExtendedRecord.  # noqa: E501


        :return: The movie_id of this ArtworkExtendedRecord.  # noqa: E501
        :rtype: int
        """
        return self._movie_id

    @movie_id.setter
    def movie_id(self, movie_id):
        """Sets the movie_id of this ArtworkExtendedRecord.


        :param movie_id: The movie_id of this ArtworkExtendedRecord.  # noqa: E501
        :type movie_id: int
        """

        self._movie_id = movie_id

    @property
    def network_id(self):
        """Gets the network_id of this ArtworkExtendedRecord.  # noqa: E501


        :return: The network_id of this ArtworkExtendedRecord.  # noqa: E501
        :rtype: int
        """
        return self._network_id

    @network_id.setter
    def network_id(self, network_id):
        """Sets the network_id of this ArtworkExtendedRecord.


        :param network_id: The network_id of this ArtworkExtendedRecord.  # noqa: E501
        :type network_id: int
        """

        self._network_id = network_id

    @property
    def people_id(self):
        """Gets the people_id of this ArtworkExtendedRecord.  # noqa: E501


        :return: The people_id of this ArtworkExtendedRecord.  # noqa: E501
        :rtype: int
        """
        return self._people_id

    @people_id.setter
    def people_id(self, people_id):
        """Sets the people_id of this ArtworkExtendedRecord.


        :param people_id: The people_id of this ArtworkExtendedRecord.  # noqa: E501
        :type people_id: int
        """

        self._people_id = people_id

    @property
    def score(self):
        """Gets the score of this ArtworkExtendedRecord.  # noqa: E501


        :return: The score of this ArtworkExtendedRecord.  # noqa: E501
        :rtype: float
        """
        return self._score

    @score.setter
    def score(self, score):
        """Sets the score of this ArtworkExtendedRecord.


        :param score: The score of this ArtworkExtendedRecord.  # noqa: E501
        :type score: float
        """

        self._score = score

    @property
    def season_id(self):
        """Gets the season_id of this ArtworkExtendedRecord.  # noqa: E501


        :return: The season_id of this ArtworkExtendedRecord.  # noqa: E501
        :rtype: int
        """
        return self._season_id

    @season_id.setter
    def season_id(self, season_id):
        """Sets the season_id of this ArtworkExtendedRecord.


        :param season_id: The season_id of this ArtworkExtendedRecord.  # noqa: E501
        :type season_id: int
        """

        self._season_id = season_id

    @property
    def series_id(self):
        """Gets the series_id of this ArtworkExtendedRecord.  # noqa: E501


        :return: The series_id of this ArtworkExtendedRecord.  # noqa: E501
        :rtype: int
        """
        return self._series_id

    @series_id.setter
    def series_id(self, series_id):
        """Sets the series_id of this ArtworkExtendedRecord.


        :param series_id: The series_id of this ArtworkExtendedRecord.  # noqa: E501
        :type series_id: int
        """

        self._series_id = series_id

    @property
    def series_people_id(self):
        """Gets the series_people_id of this ArtworkExtendedRecord.  # noqa: E501


        :return: The series_people_id of this ArtworkExtendedRecord.  # noqa: E501
        :rtype: int
        """
        return self._series_people_id

    @series_people_id.setter
    def series_people_id(self, series_people_id):
        """Sets the series_people_id of this ArtworkExtendedRecord.


        :param series_people_id: The series_people_id of this ArtworkExtendedRecord.  # noqa: E501
        :type series_people_id: int
        """

        self._series_people_id = series_people_id

    @property
    def thumbnail(self):
        """Gets the thumbnail of this ArtworkExtendedRecord.  # noqa: E501


        :return: The thumbnail of this ArtworkExtendedRecord.  # noqa: E501
        :rtype: str
        """
        return self._thumbnail

    @thumbnail.setter
    def thumbnail(self, thumbnail):
        """Sets the thumbnail of this ArtworkExtendedRecord.


        :param thumbnail: The thumbnail of this ArtworkExtendedRecord.  # noqa: E501
        :type thumbnail: str
        """

        self._thumbnail = thumbnail

    @property
    def thumbnail_height(self):
        """Gets the thumbnail_height of this ArtworkExtendedRecord.  # noqa: E501


        :return: The thumbnail_height of this ArtworkExtendedRecord.  # noqa: E501
        :rtype: int
        """
        return self._thumbnail_height

    @thumbnail_height.setter
    def thumbnail_height(self, thumbnail_height):
        """Sets the thumbnail_height of this ArtworkExtendedRecord.


        :param thumbnail_height: The thumbnail_height of this ArtworkExtendedRecord.  # noqa: E501
        :type thumbnail_height: int
        """

        self._thumbnail_height = thumbnail_height

    @property
    def thumbnail_width(self):
        """Gets the thumbnail_width of this ArtworkExtendedRecord.  # noqa: E501


        :return: The thumbnail_width of this ArtworkExtendedRecord.  # noqa: E501
        :rtype: int
        """
        return self._thumbnail_width

    @thumbnail_width.setter
    def thumbnail_width(self, thumbnail_width):
        """Sets the thumbnail_width of this ArtworkExtendedRecord.


        :param thumbnail_width: The thumbnail_width of this ArtworkExtendedRecord.  # noqa: E501
        :type thumbnail_width: int
        """

        self._thumbnail_width = thumbnail_width

    @property
    def type(self):
        """Gets the type of this ArtworkExtendedRecord.  # noqa: E501


        :return: The type of this ArtworkExtendedRecord.  # noqa: E501
        :rtype: int
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this ArtworkExtendedRecord.


        :param type: The type of this ArtworkExtendedRecord.  # noqa: E501
        :type type: int
        """

        self._type = type

    @property
    def updated_at(self):
        """Gets the updated_at of this ArtworkExtendedRecord.  # noqa: E501


        :return: The updated_at of this ArtworkExtendedRecord.  # noqa: E501
        :rtype: int
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at):
        """Sets the updated_at of this ArtworkExtendedRecord.


        :param updated_at: The updated_at of this ArtworkExtendedRecord.  # noqa: E501
        :type updated_at: int
        """

        self._updated_at = updated_at

    @property
    def width(self):
        """Gets the width of this ArtworkExtendedRecord.  # noqa: E501


        :return: The width of this ArtworkExtendedRecord.  # noqa: E501
        :rtype: int
        """
        return self._width

    @width.setter
    def width(self, width):
        """Sets the width of this ArtworkExtendedRecord.


        :param width: The width of this ArtworkExtendedRecord.  # noqa: E501
        :type width: int
        """

        self._width = width

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = inspect.getargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ArtworkExtendedRecord):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ArtworkExtendedRecord):
            return True

        return self.to_dict() != other.to_dict()
