# coding: utf-8

"""
    TVDB API V4

    Documentation of the TVDB API V4  # noqa: E501

    The version of the OpenAPI document: 4.3.0
    Generated by: https://openapi-generator.tech
"""


import inspect
import pprint
import re  # noqa: F401
import six

from openapi_client.configuration import Configuration


class ArtworkType(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'height': 'int',
        'id': 'int',
        'image_format': 'str',
        'name': 'str',
        'record_type': 'str',
        'slug': 'str',
        'thumb_height': 'int',
        'thumb_width': 'int',
        'width': 'int'
    }

    attribute_map = {
        'height': 'height',
        'id': 'id',
        'image_format': 'imageFormat',
        'name': 'name',
        'record_type': 'recordType',
        'slug': 'slug',
        'thumb_height': 'thumbHeight',
        'thumb_width': 'thumbWidth',
        'width': 'width'
    }

    def __init__(self, height=None, id=None, image_format=None, name=None, record_type=None, slug=None, thumb_height=None, thumb_width=None, width=None, local_vars_configuration=None):  # noqa: E501
        """ArtworkType - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._height = None
        self._id = None
        self._image_format = None
        self._name = None
        self._record_type = None
        self._slug = None
        self._thumb_height = None
        self._thumb_width = None
        self._width = None
        self.discriminator = None

        if height is not None:
            self.height = height
        if id is not None:
            self.id = id
        if image_format is not None:
            self.image_format = image_format
        if name is not None:
            self.name = name
        if record_type is not None:
            self.record_type = record_type
        if slug is not None:
            self.slug = slug
        if thumb_height is not None:
            self.thumb_height = thumb_height
        if thumb_width is not None:
            self.thumb_width = thumb_width
        if width is not None:
            self.width = width

    @property
    def height(self):
        """Gets the height of this ArtworkType.  # noqa: E501


        :return: The height of this ArtworkType.  # noqa: E501
        :rtype: int
        """
        return self._height

    @height.setter
    def height(self, height):
        """Sets the height of this ArtworkType.


        :param height: The height of this ArtworkType.  # noqa: E501
        :type height: int
        """

        self._height = height

    @property
    def id(self):
        """Gets the id of this ArtworkType.  # noqa: E501


        :return: The id of this ArtworkType.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ArtworkType.


        :param id: The id of this ArtworkType.  # noqa: E501
        :type id: int
        """

        self._id = id

    @property
    def image_format(self):
        """Gets the image_format of this ArtworkType.  # noqa: E501


        :return: The image_format of this ArtworkType.  # noqa: E501
        :rtype: str
        """
        return self._image_format

    @image_format.setter
    def image_format(self, image_format):
        """Sets the image_format of this ArtworkType.


        :param image_format: The image_format of this ArtworkType.  # noqa: E501
        :type image_format: str
        """

        self._image_format = image_format

    @property
    def name(self):
        """Gets the name of this ArtworkType.  # noqa: E501


        :return: The name of this ArtworkType.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ArtworkType.


        :param name: The name of this ArtworkType.  # noqa: E501
        :type name: str
        """

        self._name = name

    @property
    def record_type(self):
        """Gets the record_type of this ArtworkType.  # noqa: E501


        :return: The record_type of this ArtworkType.  # noqa: E501
        :rtype: str
        """
        return self._record_type

    @record_type.setter
    def record_type(self, record_type):
        """Sets the record_type of this ArtworkType.


        :param record_type: The record_type of this ArtworkType.  # noqa: E501
        :type record_type: str
        """

        self._record_type = record_type

    @property
    def slug(self):
        """Gets the slug of this ArtworkType.  # noqa: E501


        :return: The slug of this ArtworkType.  # noqa: E501
        :rtype: str
        """
        return self._slug

    @slug.setter
    def slug(self, slug):
        """Sets the slug of this ArtworkType.


        :param slug: The slug of this ArtworkType.  # noqa: E501
        :type slug: str
        """

        self._slug = slug

    @property
    def thumb_height(self):
        """Gets the thumb_height of this ArtworkType.  # noqa: E501


        :return: The thumb_height of this ArtworkType.  # noqa: E501
        :rtype: int
        """
        return self._thumb_height

    @thumb_height.setter
    def thumb_height(self, thumb_height):
        """Sets the thumb_height of this ArtworkType.


        :param thumb_height: The thumb_height of this ArtworkType.  # noqa: E501
        :type thumb_height: int
        """

        self._thumb_height = thumb_height

    @property
    def thumb_width(self):
        """Gets the thumb_width of this ArtworkType.  # noqa: E501


        :return: The thumb_width of this ArtworkType.  # noqa: E501
        :rtype: int
        """
        return self._thumb_width

    @thumb_width.setter
    def thumb_width(self, thumb_width):
        """Sets the thumb_width of this ArtworkType.


        :param thumb_width: The thumb_width of this ArtworkType.  # noqa: E501
        :type thumb_width: int
        """

        self._thumb_width = thumb_width

    @property
    def width(self):
        """Gets the width of this ArtworkType.  # noqa: E501


        :return: The width of this ArtworkType.  # noqa: E501
        :rtype: int
        """
        return self._width

    @width.setter
    def width(self, width):
        """Sets the width of this ArtworkType.


        :param width: The width of this ArtworkType.  # noqa: E501
        :type width: int
        """

        self._width = width

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = inspect.getargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ArtworkType):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ArtworkType):
            return True

        return self.to_dict() != other.to_dict()
