# coding: utf-8

"""
    TVDB API V4

    Documentation of the TVDB API V4  # noqa: E501

    The version of the OpenAPI document: 4.3.0
    Generated by: https://openapi-generator.tech
"""


import inspect
import pprint
import re  # noqa: F401
import six

from openapi_client.configuration import Configuration


class AwardCategoryBaseRecord(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'allow_co_nominees': 'bool',
        'award': 'AwardBaseRecord',
        'for_movies': 'bool',
        'for_series': 'bool',
        'id': 'int',
        'name': 'str'
    }

    attribute_map = {
        'allow_co_nominees': 'allowCoNominees',
        'award': 'award',
        'for_movies': 'forMovies',
        'for_series': 'forSeries',
        'id': 'id',
        'name': 'name'
    }

    def __init__(self, allow_co_nominees=None, award=None, for_movies=None, for_series=None, id=None, name=None, local_vars_configuration=None):  # noqa: E501
        """AwardCategoryBaseRecord - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._allow_co_nominees = None
        self._award = None
        self._for_movies = None
        self._for_series = None
        self._id = None
        self._name = None
        self.discriminator = None

        if allow_co_nominees is not None:
            self.allow_co_nominees = allow_co_nominees
        if award is not None:
            self.award = award
        if for_movies is not None:
            self.for_movies = for_movies
        if for_series is not None:
            self.for_series = for_series
        if id is not None:
            self.id = id
        if name is not None:
            self.name = name

    @property
    def allow_co_nominees(self):
        """Gets the allow_co_nominees of this AwardCategoryBaseRecord.  # noqa: E501


        :return: The allow_co_nominees of this AwardCategoryBaseRecord.  # noqa: E501
        :rtype: bool
        """
        return self._allow_co_nominees

    @allow_co_nominees.setter
    def allow_co_nominees(self, allow_co_nominees):
        """Sets the allow_co_nominees of this AwardCategoryBaseRecord.


        :param allow_co_nominees: The allow_co_nominees of this AwardCategoryBaseRecord.  # noqa: E501
        :type allow_co_nominees: bool
        """

        self._allow_co_nominees = allow_co_nominees

    @property
    def award(self):
        """Gets the award of this AwardCategoryBaseRecord.  # noqa: E501


        :return: The award of this AwardCategoryBaseRecord.  # noqa: E501
        :rtype: AwardBaseRecord
        """
        return self._award

    @award.setter
    def award(self, award):
        """Sets the award of this AwardCategoryBaseRecord.


        :param award: The award of this AwardCategoryBaseRecord.  # noqa: E501
        :type award: AwardBaseRecord
        """

        self._award = award

    @property
    def for_movies(self):
        """Gets the for_movies of this AwardCategoryBaseRecord.  # noqa: E501


        :return: The for_movies of this AwardCategoryBaseRecord.  # noqa: E501
        :rtype: bool
        """
        return self._for_movies

    @for_movies.setter
    def for_movies(self, for_movies):
        """Sets the for_movies of this AwardCategoryBaseRecord.


        :param for_movies: The for_movies of this AwardCategoryBaseRecord.  # noqa: E501
        :type for_movies: bool
        """

        self._for_movies = for_movies

    @property
    def for_series(self):
        """Gets the for_series of this AwardCategoryBaseRecord.  # noqa: E501


        :return: The for_series of this AwardCategoryBaseRecord.  # noqa: E501
        :rtype: bool
        """
        return self._for_series

    @for_series.setter
    def for_series(self, for_series):
        """Sets the for_series of this AwardCategoryBaseRecord.


        :param for_series: The for_series of this AwardCategoryBaseRecord.  # noqa: E501
        :type for_series: bool
        """

        self._for_series = for_series

    @property
    def id(self):
        """Gets the id of this AwardCategoryBaseRecord.  # noqa: E501


        :return: The id of this AwardCategoryBaseRecord.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this AwardCategoryBaseRecord.


        :param id: The id of this AwardCategoryBaseRecord.  # noqa: E501
        :type id: int
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this AwardCategoryBaseRecord.  # noqa: E501


        :return: The name of this AwardCategoryBaseRecord.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this AwardCategoryBaseRecord.


        :param name: The name of this AwardCategoryBaseRecord.  # noqa: E501
        :type name: str
        """

        self._name = name

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = inspect.getargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AwardCategoryBaseRecord):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, AwardCategoryBaseRecord):
            return True

        return self.to_dict() != other.to_dict()
