# coding: utf-8

"""
    TVDB API V4

    Documentation of the TVDB API V4  # noqa: E501

    The version of the OpenAPI document: 4.3.0
    Generated by: https://openapi-generator.tech
"""


import inspect
import pprint
import re  # noqa: F401
import six

from openapi_client.configuration import Configuration


class EntityUpdate(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'entity_type': 'str',
        'method': 'str',
        'record_id': 'int',
        'time_stamp': 'int'
    }

    attribute_map = {
        'entity_type': 'entityType',
        'method': 'method',
        'record_id': 'recordId',
        'time_stamp': 'timeStamp'
    }

    def __init__(self, entity_type=None, method=None, record_id=None, time_stamp=None, local_vars_configuration=None):  # noqa: E501
        """EntityUpdate - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._entity_type = None
        self._method = None
        self._record_id = None
        self._time_stamp = None
        self.discriminator = None

        if entity_type is not None:
            self.entity_type = entity_type
        if method is not None:
            self.method = method
        if record_id is not None:
            self.record_id = record_id
        if time_stamp is not None:
            self.time_stamp = time_stamp

    @property
    def entity_type(self):
        """Gets the entity_type of this EntityUpdate.  # noqa: E501


        :return: The entity_type of this EntityUpdate.  # noqa: E501
        :rtype: str
        """
        return self._entity_type

    @entity_type.setter
    def entity_type(self, entity_type):
        """Sets the entity_type of this EntityUpdate.


        :param entity_type: The entity_type of this EntityUpdate.  # noqa: E501
        :type entity_type: str
        """

        self._entity_type = entity_type

    @property
    def method(self):
        """Gets the method of this EntityUpdate.  # noqa: E501


        :return: The method of this EntityUpdate.  # noqa: E501
        :rtype: str
        """
        return self._method

    @method.setter
    def method(self, method):
        """Sets the method of this EntityUpdate.


        :param method: The method of this EntityUpdate.  # noqa: E501
        :type method: str
        """

        self._method = method

    @property
    def record_id(self):
        """Gets the record_id of this EntityUpdate.  # noqa: E501


        :return: The record_id of this EntityUpdate.  # noqa: E501
        :rtype: int
        """
        return self._record_id

    @record_id.setter
    def record_id(self, record_id):
        """Sets the record_id of this EntityUpdate.


        :param record_id: The record_id of this EntityUpdate.  # noqa: E501
        :type record_id: int
        """

        self._record_id = record_id

    @property
    def time_stamp(self):
        """Gets the time_stamp of this EntityUpdate.  # noqa: E501


        :return: The time_stamp of this EntityUpdate.  # noqa: E501
        :rtype: int
        """
        return self._time_stamp

    @time_stamp.setter
    def time_stamp(self, time_stamp):
        """Sets the time_stamp of this EntityUpdate.


        :param time_stamp: The time_stamp of this EntityUpdate.  # noqa: E501
        :type time_stamp: int
        """

        self._time_stamp = time_stamp

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = inspect.getargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EntityUpdate):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, EntityUpdate):
            return True

        return self.to_dict() != other.to_dict()
