# coding: utf-8

"""
    TVDB API V4

    Documentation of the TVDB API V4  # noqa: E501

    The version of the OpenAPI document: 4.3.0
    Generated by: https://openapi-generator.tech
"""


import inspect
import pprint
import re  # noqa: F401
import six

from openapi_client.configuration import Configuration


class EpisodeExtendedRecord(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'aired': 'str',
        'airs_after_season': 'int',
        'airs_before_episode': 'int',
        'airs_before_season': 'int',
        'awards': 'list[AwardBaseRecord]',
        'characters': 'list[Character]',
        'content_ratings': 'list[ContentRating]',
        'id': 'int',
        'image': 'str',
        'image_type': 'int',
        'is_movie': 'int',
        'name': 'str',
        'name_translations': 'list[str]',
        'network': 'NetworkBaseRecord',
        'number': 'int',
        'overview_translations': 'list[str]',
        'production_code': 'str',
        'remote_ids': 'list[RemoteID]',
        'runtime': 'int',
        'season_number': 'int',
        'seasons': 'list[SeasonBaseRecord]',
        'series_id': 'int',
        'tag_options': 'list[TagOption]',
        'trailers': 'list[Trailer]'
    }

    attribute_map = {
        'aired': 'aired',
        'airs_after_season': 'airsAfterSeason',
        'airs_before_episode': 'airsBeforeEpisode',
        'airs_before_season': 'airsBeforeSeason',
        'awards': 'awards',
        'characters': 'characters',
        'content_ratings': 'contentRatings',
        'id': 'id',
        'image': 'image',
        'image_type': 'imageType',
        'is_movie': 'isMovie',
        'name': 'name',
        'name_translations': 'nameTranslations',
        'network': 'network',
        'number': 'number',
        'overview_translations': 'overviewTranslations',
        'production_code': 'productionCode',
        'remote_ids': 'remoteIds',
        'runtime': 'runtime',
        'season_number': 'seasonNumber',
        'seasons': 'seasons',
        'series_id': 'seriesId',
        'tag_options': 'tagOptions',
        'trailers': 'trailers'
    }

    def __init__(self, aired=None, airs_after_season=None, airs_before_episode=None, airs_before_season=None, awards=None, characters=None, content_ratings=None, id=None, image=None, image_type=None, is_movie=None, name=None, name_translations=None, network=None, number=None, overview_translations=None, production_code=None, remote_ids=None, runtime=None, season_number=None, seasons=None, series_id=None, tag_options=None, trailers=None, local_vars_configuration=None):  # noqa: E501
        """EpisodeExtendedRecord - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._aired = None
        self._airs_after_season = None
        self._airs_before_episode = None
        self._airs_before_season = None
        self._awards = None
        self._characters = None
        self._content_ratings = None
        self._id = None
        self._image = None
        self._image_type = None
        self._is_movie = None
        self._name = None
        self._name_translations = None
        self._network = None
        self._number = None
        self._overview_translations = None
        self._production_code = None
        self._remote_ids = None
        self._runtime = None
        self._season_number = None
        self._seasons = None
        self._series_id = None
        self._tag_options = None
        self._trailers = None
        self.discriminator = None

        if aired is not None:
            self.aired = aired
        if airs_after_season is not None:
            self.airs_after_season = airs_after_season
        if airs_before_episode is not None:
            self.airs_before_episode = airs_before_episode
        if airs_before_season is not None:
            self.airs_before_season = airs_before_season
        if awards is not None:
            self.awards = awards
        if characters is not None:
            self.characters = characters
        if content_ratings is not None:
            self.content_ratings = content_ratings
        if id is not None:
            self.id = id
        if image is not None:
            self.image = image
        if image_type is not None:
            self.image_type = image_type
        if is_movie is not None:
            self.is_movie = is_movie
        if name is not None:
            self.name = name
        if name_translations is not None:
            self.name_translations = name_translations
        if network is not None:
            self.network = network
        if number is not None:
            self.number = number
        if overview_translations is not None:
            self.overview_translations = overview_translations
        if production_code is not None:
            self.production_code = production_code
        if remote_ids is not None:
            self.remote_ids = remote_ids
        if runtime is not None:
            self.runtime = runtime
        if season_number is not None:
            self.season_number = season_number
        if seasons is not None:
            self.seasons = seasons
        if series_id is not None:
            self.series_id = series_id
        if tag_options is not None:
            self.tag_options = tag_options
        if trailers is not None:
            self.trailers = trailers

    @property
    def aired(self):
        """Gets the aired of this EpisodeExtendedRecord.  # noqa: E501


        :return: The aired of this EpisodeExtendedRecord.  # noqa: E501
        :rtype: str
        """
        return self._aired

    @aired.setter
    def aired(self, aired):
        """Sets the aired of this EpisodeExtendedRecord.


        :param aired: The aired of this EpisodeExtendedRecord.  # noqa: E501
        :type aired: str
        """

        self._aired = aired

    @property
    def airs_after_season(self):
        """Gets the airs_after_season of this EpisodeExtendedRecord.  # noqa: E501


        :return: The airs_after_season of this EpisodeExtendedRecord.  # noqa: E501
        :rtype: int
        """
        return self._airs_after_season

    @airs_after_season.setter
    def airs_after_season(self, airs_after_season):
        """Sets the airs_after_season of this EpisodeExtendedRecord.


        :param airs_after_season: The airs_after_season of this EpisodeExtendedRecord.  # noqa: E501
        :type airs_after_season: int
        """

        self._airs_after_season = airs_after_season

    @property
    def airs_before_episode(self):
        """Gets the airs_before_episode of this EpisodeExtendedRecord.  # noqa: E501


        :return: The airs_before_episode of this EpisodeExtendedRecord.  # noqa: E501
        :rtype: int
        """
        return self._airs_before_episode

    @airs_before_episode.setter
    def airs_before_episode(self, airs_before_episode):
        """Sets the airs_before_episode of this EpisodeExtendedRecord.


        :param airs_before_episode: The airs_before_episode of this EpisodeExtendedRecord.  # noqa: E501
        :type airs_before_episode: int
        """

        self._airs_before_episode = airs_before_episode

    @property
    def airs_before_season(self):
        """Gets the airs_before_season of this EpisodeExtendedRecord.  # noqa: E501


        :return: The airs_before_season of this EpisodeExtendedRecord.  # noqa: E501
        :rtype: int
        """
        return self._airs_before_season

    @airs_before_season.setter
    def airs_before_season(self, airs_before_season):
        """Sets the airs_before_season of this EpisodeExtendedRecord.


        :param airs_before_season: The airs_before_season of this EpisodeExtendedRecord.  # noqa: E501
        :type airs_before_season: int
        """

        self._airs_before_season = airs_before_season

    @property
    def awards(self):
        """Gets the awards of this EpisodeExtendedRecord.  # noqa: E501


        :return: The awards of this EpisodeExtendedRecord.  # noqa: E501
        :rtype: list[AwardBaseRecord]
        """
        return self._awards

    @awards.setter
    def awards(self, awards):
        """Sets the awards of this EpisodeExtendedRecord.


        :param awards: The awards of this EpisodeExtendedRecord.  # noqa: E501
        :type awards: list[AwardBaseRecord]
        """

        self._awards = awards

    @property
    def characters(self):
        """Gets the characters of this EpisodeExtendedRecord.  # noqa: E501


        :return: The characters of this EpisodeExtendedRecord.  # noqa: E501
        :rtype: list[Character]
        """
        return self._characters

    @characters.setter
    def characters(self, characters):
        """Sets the characters of this EpisodeExtendedRecord.


        :param characters: The characters of this EpisodeExtendedRecord.  # noqa: E501
        :type characters: list[Character]
        """

        self._characters = characters

    @property
    def content_ratings(self):
        """Gets the content_ratings of this EpisodeExtendedRecord.  # noqa: E501


        :return: The content_ratings of this EpisodeExtendedRecord.  # noqa: E501
        :rtype: list[ContentRating]
        """
        return self._content_ratings

    @content_ratings.setter
    def content_ratings(self, content_ratings):
        """Sets the content_ratings of this EpisodeExtendedRecord.


        :param content_ratings: The content_ratings of this EpisodeExtendedRecord.  # noqa: E501
        :type content_ratings: list[ContentRating]
        """

        self._content_ratings = content_ratings

    @property
    def id(self):
        """Gets the id of this EpisodeExtendedRecord.  # noqa: E501


        :return: The id of this EpisodeExtendedRecord.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this EpisodeExtendedRecord.


        :param id: The id of this EpisodeExtendedRecord.  # noqa: E501
        :type id: int
        """

        self._id = id

    @property
    def image(self):
        """Gets the image of this EpisodeExtendedRecord.  # noqa: E501


        :return: The image of this EpisodeExtendedRecord.  # noqa: E501
        :rtype: str
        """
        return self._image

    @image.setter
    def image(self, image):
        """Sets the image of this EpisodeExtendedRecord.


        :param image: The image of this EpisodeExtendedRecord.  # noqa: E501
        :type image: str
        """

        self._image = image

    @property
    def image_type(self):
        """Gets the image_type of this EpisodeExtendedRecord.  # noqa: E501


        :return: The image_type of this EpisodeExtendedRecord.  # noqa: E501
        :rtype: int
        """
        return self._image_type

    @image_type.setter
    def image_type(self, image_type):
        """Sets the image_type of this EpisodeExtendedRecord.


        :param image_type: The image_type of this EpisodeExtendedRecord.  # noqa: E501
        :type image_type: int
        """

        self._image_type = image_type

    @property
    def is_movie(self):
        """Gets the is_movie of this EpisodeExtendedRecord.  # noqa: E501


        :return: The is_movie of this EpisodeExtendedRecord.  # noqa: E501
        :rtype: int
        """
        return self._is_movie

    @is_movie.setter
    def is_movie(self, is_movie):
        """Sets the is_movie of this EpisodeExtendedRecord.


        :param is_movie: The is_movie of this EpisodeExtendedRecord.  # noqa: E501
        :type is_movie: int
        """

        self._is_movie = is_movie

    @property
    def name(self):
        """Gets the name of this EpisodeExtendedRecord.  # noqa: E501


        :return: The name of this EpisodeExtendedRecord.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this EpisodeExtendedRecord.


        :param name: The name of this EpisodeExtendedRecord.  # noqa: E501
        :type name: str
        """

        self._name = name

    @property
    def name_translations(self):
        """Gets the name_translations of this EpisodeExtendedRecord.  # noqa: E501


        :return: The name_translations of this EpisodeExtendedRecord.  # noqa: E501
        :rtype: list[str]
        """
        return self._name_translations

    @name_translations.setter
    def name_translations(self, name_translations):
        """Sets the name_translations of this EpisodeExtendedRecord.


        :param name_translations: The name_translations of this EpisodeExtendedRecord.  # noqa: E501
        :type name_translations: list[str]
        """

        self._name_translations = name_translations

    @property
    def network(self):
        """Gets the network of this EpisodeExtendedRecord.  # noqa: E501


        :return: The network of this EpisodeExtendedRecord.  # noqa: E501
        :rtype: NetworkBaseRecord
        """
        return self._network

    @network.setter
    def network(self, network):
        """Sets the network of this EpisodeExtendedRecord.


        :param network: The network of this EpisodeExtendedRecord.  # noqa: E501
        :type network: NetworkBaseRecord
        """

        self._network = network

    @property
    def number(self):
        """Gets the number of this EpisodeExtendedRecord.  # noqa: E501


        :return: The number of this EpisodeExtendedRecord.  # noqa: E501
        :rtype: int
        """
        return self._number

    @number.setter
    def number(self, number):
        """Sets the number of this EpisodeExtendedRecord.


        :param number: The number of this EpisodeExtendedRecord.  # noqa: E501
        :type number: int
        """

        self._number = number

    @property
    def overview_translations(self):
        """Gets the overview_translations of this EpisodeExtendedRecord.  # noqa: E501


        :return: The overview_translations of this EpisodeExtendedRecord.  # noqa: E501
        :rtype: list[str]
        """
        return self._overview_translations

    @overview_translations.setter
    def overview_translations(self, overview_translations):
        """Sets the overview_translations of this EpisodeExtendedRecord.


        :param overview_translations: The overview_translations of this EpisodeExtendedRecord.  # noqa: E501
        :type overview_translations: list[str]
        """

        self._overview_translations = overview_translations

    @property
    def production_code(self):
        """Gets the production_code of this EpisodeExtendedRecord.  # noqa: E501


        :return: The production_code of this EpisodeExtendedRecord.  # noqa: E501
        :rtype: str
        """
        return self._production_code

    @production_code.setter
    def production_code(self, production_code):
        """Sets the production_code of this EpisodeExtendedRecord.


        :param production_code: The production_code of this EpisodeExtendedRecord.  # noqa: E501
        :type production_code: str
        """

        self._production_code = production_code

    @property
    def remote_ids(self):
        """Gets the remote_ids of this EpisodeExtendedRecord.  # noqa: E501


        :return: The remote_ids of this EpisodeExtendedRecord.  # noqa: E501
        :rtype: list[RemoteID]
        """
        return self._remote_ids

    @remote_ids.setter
    def remote_ids(self, remote_ids):
        """Sets the remote_ids of this EpisodeExtendedRecord.


        :param remote_ids: The remote_ids of this EpisodeExtendedRecord.  # noqa: E501
        :type remote_ids: list[RemoteID]
        """

        self._remote_ids = remote_ids

    @property
    def runtime(self):
        """Gets the runtime of this EpisodeExtendedRecord.  # noqa: E501


        :return: The runtime of this EpisodeExtendedRecord.  # noqa: E501
        :rtype: int
        """
        return self._runtime

    @runtime.setter
    def runtime(self, runtime):
        """Sets the runtime of this EpisodeExtendedRecord.


        :param runtime: The runtime of this EpisodeExtendedRecord.  # noqa: E501
        :type runtime: int
        """

        self._runtime = runtime

    @property
    def season_number(self):
        """Gets the season_number of this EpisodeExtendedRecord.  # noqa: E501


        :return: The season_number of this EpisodeExtendedRecord.  # noqa: E501
        :rtype: int
        """
        return self._season_number

    @season_number.setter
    def season_number(self, season_number):
        """Sets the season_number of this EpisodeExtendedRecord.


        :param season_number: The season_number of this EpisodeExtendedRecord.  # noqa: E501
        :type season_number: int
        """

        self._season_number = season_number

    @property
    def seasons(self):
        """Gets the seasons of this EpisodeExtendedRecord.  # noqa: E501


        :return: The seasons of this EpisodeExtendedRecord.  # noqa: E501
        :rtype: list[SeasonBaseRecord]
        """
        return self._seasons

    @seasons.setter
    def seasons(self, seasons):
        """Sets the seasons of this EpisodeExtendedRecord.


        :param seasons: The seasons of this EpisodeExtendedRecord.  # noqa: E501
        :type seasons: list[SeasonBaseRecord]
        """

        self._seasons = seasons

    @property
    def series_id(self):
        """Gets the series_id of this EpisodeExtendedRecord.  # noqa: E501


        :return: The series_id of this EpisodeExtendedRecord.  # noqa: E501
        :rtype: int
        """
        return self._series_id

    @series_id.setter
    def series_id(self, series_id):
        """Sets the series_id of this EpisodeExtendedRecord.


        :param series_id: The series_id of this EpisodeExtendedRecord.  # noqa: E501
        :type series_id: int
        """

        self._series_id = series_id

    @property
    def tag_options(self):
        """Gets the tag_options of this EpisodeExtendedRecord.  # noqa: E501


        :return: The tag_options of this EpisodeExtendedRecord.  # noqa: E501
        :rtype: list[TagOption]
        """
        return self._tag_options

    @tag_options.setter
    def tag_options(self, tag_options):
        """Sets the tag_options of this EpisodeExtendedRecord.


        :param tag_options: The tag_options of this EpisodeExtendedRecord.  # noqa: E501
        :type tag_options: list[TagOption]
        """

        self._tag_options = tag_options

    @property
    def trailers(self):
        """Gets the trailers of this EpisodeExtendedRecord.  # noqa: E501


        :return: The trailers of this EpisodeExtendedRecord.  # noqa: E501
        :rtype: list[Trailer]
        """
        return self._trailers

    @trailers.setter
    def trailers(self, trailers):
        """Sets the trailers of this EpisodeExtendedRecord.


        :param trailers: The trailers of this EpisodeExtendedRecord.  # noqa: E501
        :type trailers: list[Trailer]
        """

        self._trailers = trailers

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = inspect.getargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EpisodeExtendedRecord):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, EpisodeExtendedRecord):
            return True

        return self.to_dict() != other.to_dict()
