# coding: utf-8

"""
    TVDB API V4

    Documentation of the TVDB API V4  # noqa: E501

    The version of the OpenAPI document: 4.3.0
    Generated by: https://openapi-generator.tech
"""


import inspect
import pprint
import re  # noqa: F401
import six

from openapi_client.configuration import Configuration


class EpisodeBaseRecord(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'aired': 'str',
        'id': 'int',
        'image': 'str',
        'image_type': 'int',
        'is_movie': 'int',
        'name': 'str',
        'name_translations': 'list[str]',
        'number': 'int',
        'overview_translations': 'list[str]',
        'runtime': 'int',
        'season_number': 'int',
        'seasons': 'list[SeasonBaseRecord]',
        'series_id': 'int'
    }

    attribute_map = {
        'aired': 'aired',
        'id': 'id',
        'image': 'image',
        'image_type': 'imageType',
        'is_movie': 'isMovie',
        'name': 'name',
        'name_translations': 'nameTranslations',
        'number': 'number',
        'overview_translations': 'overviewTranslations',
        'runtime': 'runtime',
        'season_number': 'seasonNumber',
        'seasons': 'seasons',
        'series_id': 'seriesId'
    }

    def __init__(self, aired=None, id=None, image=None, image_type=None, is_movie=None, name=None, name_translations=None, number=None, overview_translations=None, runtime=None, season_number=None, seasons=None, series_id=None, local_vars_configuration=None):  # noqa: E501
        """EpisodeBaseRecord - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._aired = None
        self._id = None
        self._image = None
        self._image_type = None
        self._is_movie = None
        self._name = None
        self._name_translations = None
        self._number = None
        self._overview_translations = None
        self._runtime = None
        self._season_number = None
        self._seasons = None
        self._series_id = None
        self.discriminator = None

        if aired is not None:
            self.aired = aired
        if id is not None:
            self.id = id
        if image is not None:
            self.image = image
        if image_type is not None:
            self.image_type = image_type
        if is_movie is not None:
            self.is_movie = is_movie
        if name is not None:
            self.name = name
        if name_translations is not None:
            self.name_translations = name_translations
        if number is not None:
            self.number = number
        if overview_translations is not None:
            self.overview_translations = overview_translations
        if runtime is not None:
            self.runtime = runtime
        if season_number is not None:
            self.season_number = season_number
        if seasons is not None:
            self.seasons = seasons
        if series_id is not None:
            self.series_id = series_id

    @property
    def aired(self):
        """Gets the aired of this EpisodeBaseRecord.  # noqa: E501


        :return: The aired of this EpisodeBaseRecord.  # noqa: E501
        :rtype: str
        """
        return self._aired

    @aired.setter
    def aired(self, aired):
        """Sets the aired of this EpisodeBaseRecord.


        :param aired: The aired of this EpisodeBaseRecord.  # noqa: E501
        :type aired: str
        """

        self._aired = aired

    @property
    def id(self):
        """Gets the id of this EpisodeBaseRecord.  # noqa: E501


        :return: The id of this EpisodeBaseRecord.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this EpisodeBaseRecord.


        :param id: The id of this EpisodeBaseRecord.  # noqa: E501
        :type id: int
        """

        self._id = id

    @property
    def image(self):
        """Gets the image of this EpisodeBaseRecord.  # noqa: E501


        :return: The image of this EpisodeBaseRecord.  # noqa: E501
        :rtype: str
        """
        return self._image

    @image.setter
    def image(self, image):
        """Sets the image of this EpisodeBaseRecord.


        :param image: The image of this EpisodeBaseRecord.  # noqa: E501
        :type image: str
        """

        self._image = image

    @property
    def image_type(self):
        """Gets the image_type of this EpisodeBaseRecord.  # noqa: E501


        :return: The image_type of this EpisodeBaseRecord.  # noqa: E501
        :rtype: int
        """
        return self._image_type

    @image_type.setter
    def image_type(self, image_type):
        """Sets the image_type of this EpisodeBaseRecord.


        :param image_type: The image_type of this EpisodeBaseRecord.  # noqa: E501
        :type image_type: int
        """

        self._image_type = image_type

    @property
    def is_movie(self):
        """Gets the is_movie of this EpisodeBaseRecord.  # noqa: E501


        :return: The is_movie of this EpisodeBaseRecord.  # noqa: E501
        :rtype: int
        """
        return self._is_movie

    @is_movie.setter
    def is_movie(self, is_movie):
        """Sets the is_movie of this EpisodeBaseRecord.


        :param is_movie: The is_movie of this EpisodeBaseRecord.  # noqa: E501
        :type is_movie: int
        """

        self._is_movie = is_movie

    @property
    def name(self):
        """Gets the name of this EpisodeBaseRecord.  # noqa: E501


        :return: The name of this EpisodeBaseRecord.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this EpisodeBaseRecord.


        :param name: The name of this EpisodeBaseRecord.  # noqa: E501
        :type name: str
        """

        self._name = name

    @property
    def name_translations(self):
        """Gets the name_translations of this EpisodeBaseRecord.  # noqa: E501


        :return: The name_translations of this EpisodeBaseRecord.  # noqa: E501
        :rtype: list[str]
        """
        return self._name_translations

    @name_translations.setter
    def name_translations(self, name_translations):
        """Sets the name_translations of this EpisodeBaseRecord.


        :param name_translations: The name_translations of this EpisodeBaseRecord.  # noqa: E501
        :type name_translations: list[str]
        """

        self._name_translations = name_translations

    @property
    def number(self):
        """Gets the number of this EpisodeBaseRecord.  # noqa: E501


        :return: The number of this EpisodeBaseRecord.  # noqa: E501
        :rtype: int
        """
        return self._number

    @number.setter
    def number(self, number):
        """Sets the number of this EpisodeBaseRecord.


        :param number: The number of this EpisodeBaseRecord.  # noqa: E501
        :type number: int
        """

        self._number = number

    @property
    def overview_translations(self):
        """Gets the overview_translations of this EpisodeBaseRecord.  # noqa: E501


        :return: The overview_translations of this EpisodeBaseRecord.  # noqa: E501
        :rtype: list[str]
        """
        return self._overview_translations

    @overview_translations.setter
    def overview_translations(self, overview_translations):
        """Sets the overview_translations of this EpisodeBaseRecord.


        :param overview_translations: The overview_translations of this EpisodeBaseRecord.  # noqa: E501
        :type overview_translations: list[str]
        """

        self._overview_translations = overview_translations

    @property
    def runtime(self):
        """Gets the runtime of this EpisodeBaseRecord.  # noqa: E501


        :return: The runtime of this EpisodeBaseRecord.  # noqa: E501
        :rtype: int
        """
        return self._runtime

    @runtime.setter
    def runtime(self, runtime):
        """Sets the runtime of this EpisodeBaseRecord.


        :param runtime: The runtime of this EpisodeBaseRecord.  # noqa: E501
        :type runtime: int
        """

        self._runtime = runtime

    @property
    def season_number(self):
        """Gets the season_number of this EpisodeBaseRecord.  # noqa: E501


        :return: The season_number of this EpisodeBaseRecord.  # noqa: E501
        :rtype: int
        """
        return self._season_number

    @season_number.setter
    def season_number(self, season_number):
        """Sets the season_number of this EpisodeBaseRecord.


        :param season_number: The season_number of this EpisodeBaseRecord.  # noqa: E501
        :type season_number: int
        """

        self._season_number = season_number

    @property
    def seasons(self):
        """Gets the seasons of this EpisodeBaseRecord.  # noqa: E501


        :return: The seasons of this EpisodeBaseRecord.  # noqa: E501
        :rtype: list[SeasonBaseRecord]
        """
        return self._seasons

    @seasons.setter
    def seasons(self, seasons):
        """Sets the seasons of this EpisodeBaseRecord.


        :param seasons: The seasons of this EpisodeBaseRecord.  # noqa: E501
        :type seasons: list[SeasonBaseRecord]
        """

        self._seasons = seasons

    @property
    def series_id(self):
        """Gets the series_id of this EpisodeBaseRecord.  # noqa: E501


        :return: The series_id of this EpisodeBaseRecord.  # noqa: E501
        :rtype: int
        """
        return self._series_id

    @series_id.setter
    def series_id(self, series_id):
        """Sets the series_id of this EpisodeBaseRecord.


        :param series_id: The series_id of this EpisodeBaseRecord.  # noqa: E501
        :type series_id: int
        """

        self._series_id = series_id

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = inspect.getargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EpisodeBaseRecord):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, EpisodeBaseRecord):
            return True

        return self.to_dict() != other.to_dict()
