# coding: utf-8

"""
    TVDB API V4

    Documentation of the TVDB API V4  # noqa: E501

    The version of the OpenAPI document: 4.3.0
    Generated by: https://openapi-generator.tech
"""


import inspect
import pprint
import re  # noqa: F401
import six

from openapi_client.configuration import Configuration


class ListBaseRecord(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'aliases': 'list[Alias]',
        'id': 'int',
        'is_official': 'bool',
        'name': 'str',
        'name_translations': 'list[str]',
        'overview': 'str',
        'overview_translations': 'list[str]',
        'url': 'str'
    }

    attribute_map = {
        'aliases': 'aliases',
        'id': 'id',
        'is_official': 'isOfficial',
        'name': 'name',
        'name_translations': 'nameTranslations',
        'overview': 'overview',
        'overview_translations': 'overviewTranslations',
        'url': 'url'
    }

    def __init__(self, aliases=None, id=None, is_official=None, name=None, name_translations=None, overview=None, overview_translations=None, url=None, local_vars_configuration=None):  # noqa: E501
        """ListBaseRecord - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._aliases = None
        self._id = None
        self._is_official = None
        self._name = None
        self._name_translations = None
        self._overview = None
        self._overview_translations = None
        self._url = None
        self.discriminator = None

        if aliases is not None:
            self.aliases = aliases
        if id is not None:
            self.id = id
        if is_official is not None:
            self.is_official = is_official
        if name is not None:
            self.name = name
        if name_translations is not None:
            self.name_translations = name_translations
        if overview is not None:
            self.overview = overview
        if overview_translations is not None:
            self.overview_translations = overview_translations
        if url is not None:
            self.url = url

    @property
    def aliases(self):
        """Gets the aliases of this ListBaseRecord.  # noqa: E501


        :return: The aliases of this ListBaseRecord.  # noqa: E501
        :rtype: list[Alias]
        """
        return self._aliases

    @aliases.setter
    def aliases(self, aliases):
        """Sets the aliases of this ListBaseRecord.


        :param aliases: The aliases of this ListBaseRecord.  # noqa: E501
        :type aliases: list[Alias]
        """

        self._aliases = aliases

    @property
    def id(self):
        """Gets the id of this ListBaseRecord.  # noqa: E501


        :return: The id of this ListBaseRecord.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ListBaseRecord.


        :param id: The id of this ListBaseRecord.  # noqa: E501
        :type id: int
        """

        self._id = id

    @property
    def is_official(self):
        """Gets the is_official of this ListBaseRecord.  # noqa: E501


        :return: The is_official of this ListBaseRecord.  # noqa: E501
        :rtype: bool
        """
        return self._is_official

    @is_official.setter
    def is_official(self, is_official):
        """Sets the is_official of this ListBaseRecord.


        :param is_official: The is_official of this ListBaseRecord.  # noqa: E501
        :type is_official: bool
        """

        self._is_official = is_official

    @property
    def name(self):
        """Gets the name of this ListBaseRecord.  # noqa: E501


        :return: The name of this ListBaseRecord.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ListBaseRecord.


        :param name: The name of this ListBaseRecord.  # noqa: E501
        :type name: str
        """

        self._name = name

    @property
    def name_translations(self):
        """Gets the name_translations of this ListBaseRecord.  # noqa: E501


        :return: The name_translations of this ListBaseRecord.  # noqa: E501
        :rtype: list[str]
        """
        return self._name_translations

    @name_translations.setter
    def name_translations(self, name_translations):
        """Sets the name_translations of this ListBaseRecord.


        :param name_translations: The name_translations of this ListBaseRecord.  # noqa: E501
        :type name_translations: list[str]
        """

        self._name_translations = name_translations

    @property
    def overview(self):
        """Gets the overview of this ListBaseRecord.  # noqa: E501


        :return: The overview of this ListBaseRecord.  # noqa: E501
        :rtype: str
        """
        return self._overview

    @overview.setter
    def overview(self, overview):
        """Sets the overview of this ListBaseRecord.


        :param overview: The overview of this ListBaseRecord.  # noqa: E501
        :type overview: str
        """

        self._overview = overview

    @property
    def overview_translations(self):
        """Gets the overview_translations of this ListBaseRecord.  # noqa: E501


        :return: The overview_translations of this ListBaseRecord.  # noqa: E501
        :rtype: list[str]
        """
        return self._overview_translations

    @overview_translations.setter
    def overview_translations(self, overview_translations):
        """Sets the overview_translations of this ListBaseRecord.


        :param overview_translations: The overview_translations of this ListBaseRecord.  # noqa: E501
        :type overview_translations: list[str]
        """

        self._overview_translations = overview_translations

    @property
    def url(self):
        """Gets the url of this ListBaseRecord.  # noqa: E501


        :return: The url of this ListBaseRecord.  # noqa: E501
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url):
        """Sets the url of this ListBaseRecord.


        :param url: The url of this ListBaseRecord.  # noqa: E501
        :type url: str
        """

        self._url = url

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = inspect.getargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ListBaseRecord):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ListBaseRecord):
            return True

        return self.to_dict() != other.to_dict()
