# coding: utf-8

"""
    TVDB API V4

    Documentation of the TVDB API V4  # noqa: E501

    The version of the OpenAPI document: 4.3.0
    Generated by: https://openapi-generator.tech
"""


import inspect
import pprint
import re  # noqa: F401
import six

from openapi_client.configuration import Configuration


class MovieBaseRecord(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'aliases': 'list[Alias]',
        'id': 'int',
        'image': 'str',
        'name': 'str',
        'name_translations': 'list[str]',
        'overview_translations': 'list[str]',
        'score': 'float',
        'slug': 'str',
        'status': 'Status'
    }

    attribute_map = {
        'aliases': 'aliases',
        'id': 'id',
        'image': 'image',
        'name': 'name',
        'name_translations': 'nameTranslations',
        'overview_translations': 'overviewTranslations',
        'score': 'score',
        'slug': 'slug',
        'status': 'status'
    }

    def __init__(self, aliases=None, id=None, image=None, name=None, name_translations=None, overview_translations=None, score=None, slug=None, status=None, local_vars_configuration=None):  # noqa: E501
        """MovieBaseRecord - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._aliases = None
        self._id = None
        self._image = None
        self._name = None
        self._name_translations = None
        self._overview_translations = None
        self._score = None
        self._slug = None
        self._status = None
        self.discriminator = None

        if aliases is not None:
            self.aliases = aliases
        if id is not None:
            self.id = id
        if image is not None:
            self.image = image
        if name is not None:
            self.name = name
        if name_translations is not None:
            self.name_translations = name_translations
        if overview_translations is not None:
            self.overview_translations = overview_translations
        if score is not None:
            self.score = score
        if slug is not None:
            self.slug = slug
        if status is not None:
            self.status = status

    @property
    def aliases(self):
        """Gets the aliases of this MovieBaseRecord.  # noqa: E501


        :return: The aliases of this MovieBaseRecord.  # noqa: E501
        :rtype: list[Alias]
        """
        return self._aliases

    @aliases.setter
    def aliases(self, aliases):
        """Sets the aliases of this MovieBaseRecord.


        :param aliases: The aliases of this MovieBaseRecord.  # noqa: E501
        :type aliases: list[Alias]
        """

        self._aliases = aliases

    @property
    def id(self):
        """Gets the id of this MovieBaseRecord.  # noqa: E501


        :return: The id of this MovieBaseRecord.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this MovieBaseRecord.


        :param id: The id of this MovieBaseRecord.  # noqa: E501
        :type id: int
        """

        self._id = id

    @property
    def image(self):
        """Gets the image of this MovieBaseRecord.  # noqa: E501


        :return: The image of this MovieBaseRecord.  # noqa: E501
        :rtype: str
        """
        return self._image

    @image.setter
    def image(self, image):
        """Sets the image of this MovieBaseRecord.


        :param image: The image of this MovieBaseRecord.  # noqa: E501
        :type image: str
        """

        self._image = image

    @property
    def name(self):
        """Gets the name of this MovieBaseRecord.  # noqa: E501


        :return: The name of this MovieBaseRecord.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this MovieBaseRecord.


        :param name: The name of this MovieBaseRecord.  # noqa: E501
        :type name: str
        """

        self._name = name

    @property
    def name_translations(self):
        """Gets the name_translations of this MovieBaseRecord.  # noqa: E501


        :return: The name_translations of this MovieBaseRecord.  # noqa: E501
        :rtype: list[str]
        """
        return self._name_translations

    @name_translations.setter
    def name_translations(self, name_translations):
        """Sets the name_translations of this MovieBaseRecord.


        :param name_translations: The name_translations of this MovieBaseRecord.  # noqa: E501
        :type name_translations: list[str]
        """

        self._name_translations = name_translations

    @property
    def overview_translations(self):
        """Gets the overview_translations of this MovieBaseRecord.  # noqa: E501


        :return: The overview_translations of this MovieBaseRecord.  # noqa: E501
        :rtype: list[str]
        """
        return self._overview_translations

    @overview_translations.setter
    def overview_translations(self, overview_translations):
        """Sets the overview_translations of this MovieBaseRecord.


        :param overview_translations: The overview_translations of this MovieBaseRecord.  # noqa: E501
        :type overview_translations: list[str]
        """

        self._overview_translations = overview_translations

    @property
    def score(self):
        """Gets the score of this MovieBaseRecord.  # noqa: E501


        :return: The score of this MovieBaseRecord.  # noqa: E501
        :rtype: float
        """
        return self._score

    @score.setter
    def score(self, score):
        """Sets the score of this MovieBaseRecord.


        :param score: The score of this MovieBaseRecord.  # noqa: E501
        :type score: float
        """

        self._score = score

    @property
    def slug(self):
        """Gets the slug of this MovieBaseRecord.  # noqa: E501


        :return: The slug of this MovieBaseRecord.  # noqa: E501
        :rtype: str
        """
        return self._slug

    @slug.setter
    def slug(self, slug):
        """Sets the slug of this MovieBaseRecord.


        :param slug: The slug of this MovieBaseRecord.  # noqa: E501
        :type slug: str
        """

        self._slug = slug

    @property
    def status(self):
        """Gets the status of this MovieBaseRecord.  # noqa: E501


        :return: The status of this MovieBaseRecord.  # noqa: E501
        :rtype: Status
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this MovieBaseRecord.


        :param status: The status of this MovieBaseRecord.  # noqa: E501
        :type status: Status
        """

        self._status = status

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = inspect.getargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MovieBaseRecord):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, MovieBaseRecord):
            return True

        return self.to_dict() != other.to_dict()
