# coding: utf-8

"""
    TVDB API V4

    Documentation of the TVDB API V4  # noqa: E501

    The version of the OpenAPI document: 4.3.0
    Generated by: https://openapi-generator.tech
"""


import inspect
import pprint
import re  # noqa: F401
import six

from openapi_client.configuration import Configuration


class PeopleExtendedRecord(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'aliases': 'list[Alias]',
        'awards': 'list[AwardBaseRecord]',
        'biographies': 'list[Biography]',
        'birth': 'str',
        'birth_place': 'str',
        'characters': 'list[Character]',
        'death': 'str',
        'gender': 'int',
        'id': 'int',
        'image': 'str',
        'name': 'str',
        'races': 'list[object]',
        'remote_ids': 'list[RemoteID]',
        'score': 'int',
        'tag_options': 'list[TagOption]'
    }

    attribute_map = {
        'aliases': 'aliases',
        'awards': 'awards',
        'biographies': 'biographies',
        'birth': 'birth',
        'birth_place': 'birthPlace',
        'characters': 'characters',
        'death': 'death',
        'gender': 'gender',
        'id': 'id',
        'image': 'image',
        'name': 'name',
        'races': 'races',
        'remote_ids': 'remoteIds',
        'score': 'score',
        'tag_options': 'tagOptions'
    }

    def __init__(self, aliases=None, awards=None, biographies=None, birth=None, birth_place=None, characters=None, death=None, gender=None, id=None, image=None, name=None, races=None, remote_ids=None, score=None, tag_options=None, local_vars_configuration=None):  # noqa: E501
        """PeopleExtendedRecord - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._aliases = None
        self._awards = None
        self._biographies = None
        self._birth = None
        self._birth_place = None
        self._characters = None
        self._death = None
        self._gender = None
        self._id = None
        self._image = None
        self._name = None
        self._races = None
        self._remote_ids = None
        self._score = None
        self._tag_options = None
        self.discriminator = None

        if aliases is not None:
            self.aliases = aliases
        if awards is not None:
            self.awards = awards
        if biographies is not None:
            self.biographies = biographies
        if birth is not None:
            self.birth = birth
        if birth_place is not None:
            self.birth_place = birth_place
        if characters is not None:
            self.characters = characters
        if death is not None:
            self.death = death
        if gender is not None:
            self.gender = gender
        if id is not None:
            self.id = id
        if image is not None:
            self.image = image
        if name is not None:
            self.name = name
        if races is not None:
            self.races = races
        if remote_ids is not None:
            self.remote_ids = remote_ids
        if score is not None:
            self.score = score
        if tag_options is not None:
            self.tag_options = tag_options

    @property
    def aliases(self):
        """Gets the aliases of this PeopleExtendedRecord.  # noqa: E501


        :return: The aliases of this PeopleExtendedRecord.  # noqa: E501
        :rtype: list[Alias]
        """
        return self._aliases

    @aliases.setter
    def aliases(self, aliases):
        """Sets the aliases of this PeopleExtendedRecord.


        :param aliases: The aliases of this PeopleExtendedRecord.  # noqa: E501
        :type aliases: list[Alias]
        """

        self._aliases = aliases

    @property
    def awards(self):
        """Gets the awards of this PeopleExtendedRecord.  # noqa: E501


        :return: The awards of this PeopleExtendedRecord.  # noqa: E501
        :rtype: list[AwardBaseRecord]
        """
        return self._awards

    @awards.setter
    def awards(self, awards):
        """Sets the awards of this PeopleExtendedRecord.


        :param awards: The awards of this PeopleExtendedRecord.  # noqa: E501
        :type awards: list[AwardBaseRecord]
        """

        self._awards = awards

    @property
    def biographies(self):
        """Gets the biographies of this PeopleExtendedRecord.  # noqa: E501


        :return: The biographies of this PeopleExtendedRecord.  # noqa: E501
        :rtype: list[Biography]
        """
        return self._biographies

    @biographies.setter
    def biographies(self, biographies):
        """Sets the biographies of this PeopleExtendedRecord.


        :param biographies: The biographies of this PeopleExtendedRecord.  # noqa: E501
        :type biographies: list[Biography]
        """

        self._biographies = biographies

    @property
    def birth(self):
        """Gets the birth of this PeopleExtendedRecord.  # noqa: E501


        :return: The birth of this PeopleExtendedRecord.  # noqa: E501
        :rtype: str
        """
        return self._birth

    @birth.setter
    def birth(self, birth):
        """Sets the birth of this PeopleExtendedRecord.


        :param birth: The birth of this PeopleExtendedRecord.  # noqa: E501
        :type birth: str
        """

        self._birth = birth

    @property
    def birth_place(self):
        """Gets the birth_place of this PeopleExtendedRecord.  # noqa: E501


        :return: The birth_place of this PeopleExtendedRecord.  # noqa: E501
        :rtype: str
        """
        return self._birth_place

    @birth_place.setter
    def birth_place(self, birth_place):
        """Sets the birth_place of this PeopleExtendedRecord.


        :param birth_place: The birth_place of this PeopleExtendedRecord.  # noqa: E501
        :type birth_place: str
        """

        self._birth_place = birth_place

    @property
    def characters(self):
        """Gets the characters of this PeopleExtendedRecord.  # noqa: E501


        :return: The characters of this PeopleExtendedRecord.  # noqa: E501
        :rtype: list[Character]
        """
        return self._characters

    @characters.setter
    def characters(self, characters):
        """Sets the characters of this PeopleExtendedRecord.


        :param characters: The characters of this PeopleExtendedRecord.  # noqa: E501
        :type characters: list[Character]
        """

        self._characters = characters

    @property
    def death(self):
        """Gets the death of this PeopleExtendedRecord.  # noqa: E501


        :return: The death of this PeopleExtendedRecord.  # noqa: E501
        :rtype: str
        """
        return self._death

    @death.setter
    def death(self, death):
        """Sets the death of this PeopleExtendedRecord.


        :param death: The death of this PeopleExtendedRecord.  # noqa: E501
        :type death: str
        """

        self._death = death

    @property
    def gender(self):
        """Gets the gender of this PeopleExtendedRecord.  # noqa: E501


        :return: The gender of this PeopleExtendedRecord.  # noqa: E501
        :rtype: int
        """
        return self._gender

    @gender.setter
    def gender(self, gender):
        """Sets the gender of this PeopleExtendedRecord.


        :param gender: The gender of this PeopleExtendedRecord.  # noqa: E501
        :type gender: int
        """

        self._gender = gender

    @property
    def id(self):
        """Gets the id of this PeopleExtendedRecord.  # noqa: E501


        :return: The id of this PeopleExtendedRecord.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this PeopleExtendedRecord.


        :param id: The id of this PeopleExtendedRecord.  # noqa: E501
        :type id: int
        """

        self._id = id

    @property
    def image(self):
        """Gets the image of this PeopleExtendedRecord.  # noqa: E501


        :return: The image of this PeopleExtendedRecord.  # noqa: E501
        :rtype: str
        """
        return self._image

    @image.setter
    def image(self, image):
        """Sets the image of this PeopleExtendedRecord.


        :param image: The image of this PeopleExtendedRecord.  # noqa: E501
        :type image: str
        """

        self._image = image

    @property
    def name(self):
        """Gets the name of this PeopleExtendedRecord.  # noqa: E501


        :return: The name of this PeopleExtendedRecord.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this PeopleExtendedRecord.


        :param name: The name of this PeopleExtendedRecord.  # noqa: E501
        :type name: str
        """

        self._name = name

    @property
    def races(self):
        """Gets the races of this PeopleExtendedRecord.  # noqa: E501


        :return: The races of this PeopleExtendedRecord.  # noqa: E501
        :rtype: list[object]
        """
        return self._races

    @races.setter
    def races(self, races):
        """Sets the races of this PeopleExtendedRecord.


        :param races: The races of this PeopleExtendedRecord.  # noqa: E501
        :type races: list[object]
        """

        self._races = races

    @property
    def remote_ids(self):
        """Gets the remote_ids of this PeopleExtendedRecord.  # noqa: E501


        :return: The remote_ids of this PeopleExtendedRecord.  # noqa: E501
        :rtype: list[RemoteID]
        """
        return self._remote_ids

    @remote_ids.setter
    def remote_ids(self, remote_ids):
        """Sets the remote_ids of this PeopleExtendedRecord.


        :param remote_ids: The remote_ids of this PeopleExtendedRecord.  # noqa: E501
        :type remote_ids: list[RemoteID]
        """

        self._remote_ids = remote_ids

    @property
    def score(self):
        """Gets the score of this PeopleExtendedRecord.  # noqa: E501


        :return: The score of this PeopleExtendedRecord.  # noqa: E501
        :rtype: int
        """
        return self._score

    @score.setter
    def score(self, score):
        """Sets the score of this PeopleExtendedRecord.


        :param score: The score of this PeopleExtendedRecord.  # noqa: E501
        :type score: int
        """

        self._score = score

    @property
    def tag_options(self):
        """Gets the tag_options of this PeopleExtendedRecord.  # noqa: E501


        :return: The tag_options of this PeopleExtendedRecord.  # noqa: E501
        :rtype: list[TagOption]
        """
        return self._tag_options

    @tag_options.setter
    def tag_options(self, tag_options):
        """Sets the tag_options of this PeopleExtendedRecord.


        :param tag_options: The tag_options of this PeopleExtendedRecord.  # noqa: E501
        :type tag_options: list[TagOption]
        """

        self._tag_options = tag_options

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = inspect.getargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PeopleExtendedRecord):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, PeopleExtendedRecord):
            return True

        return self.to_dict() != other.to_dict()
