# coding: utf-8

"""
    TVDB API V4

    Documentation of the TVDB API V4  # noqa: E501

    The version of the OpenAPI document: 4.3.0
    Generated by: https://openapi-generator.tech
"""


import inspect
import pprint
import re  # noqa: F401
import six

from openapi_client.configuration import Configuration


class SeriesAirsDays(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'friday': 'bool',
        'monday': 'bool',
        'saturday': 'bool',
        'sunday': 'bool',
        'thursday': 'bool',
        'tuesday': 'bool',
        'wednesday': 'bool'
    }

    attribute_map = {
        'friday': 'friday',
        'monday': 'monday',
        'saturday': 'saturday',
        'sunday': 'sunday',
        'thursday': 'thursday',
        'tuesday': 'tuesday',
        'wednesday': 'wednesday'
    }

    def __init__(self, friday=None, monday=None, saturday=None, sunday=None, thursday=None, tuesday=None, wednesday=None, local_vars_configuration=None):  # noqa: E501
        """SeriesAirsDays - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._friday = None
        self._monday = None
        self._saturday = None
        self._sunday = None
        self._thursday = None
        self._tuesday = None
        self._wednesday = None
        self.discriminator = None

        if friday is not None:
            self.friday = friday
        if monday is not None:
            self.monday = monday
        if saturday is not None:
            self.saturday = saturday
        if sunday is not None:
            self.sunday = sunday
        if thursday is not None:
            self.thursday = thursday
        if tuesday is not None:
            self.tuesday = tuesday
        if wednesday is not None:
            self.wednesday = wednesday

    @property
    def friday(self):
        """Gets the friday of this SeriesAirsDays.  # noqa: E501


        :return: The friday of this SeriesAirsDays.  # noqa: E501
        :rtype: bool
        """
        return self._friday

    @friday.setter
    def friday(self, friday):
        """Sets the friday of this SeriesAirsDays.


        :param friday: The friday of this SeriesAirsDays.  # noqa: E501
        :type friday: bool
        """

        self._friday = friday

    @property
    def monday(self):
        """Gets the monday of this SeriesAirsDays.  # noqa: E501


        :return: The monday of this SeriesAirsDays.  # noqa: E501
        :rtype: bool
        """
        return self._monday

    @monday.setter
    def monday(self, monday):
        """Sets the monday of this SeriesAirsDays.


        :param monday: The monday of this SeriesAirsDays.  # noqa: E501
        :type monday: bool
        """

        self._monday = monday

    @property
    def saturday(self):
        """Gets the saturday of this SeriesAirsDays.  # noqa: E501


        :return: The saturday of this SeriesAirsDays.  # noqa: E501
        :rtype: bool
        """
        return self._saturday

    @saturday.setter
    def saturday(self, saturday):
        """Sets the saturday of this SeriesAirsDays.


        :param saturday: The saturday of this SeriesAirsDays.  # noqa: E501
        :type saturday: bool
        """

        self._saturday = saturday

    @property
    def sunday(self):
        """Gets the sunday of this SeriesAirsDays.  # noqa: E501


        :return: The sunday of this SeriesAirsDays.  # noqa: E501
        :rtype: bool
        """
        return self._sunday

    @sunday.setter
    def sunday(self, sunday):
        """Sets the sunday of this SeriesAirsDays.


        :param sunday: The sunday of this SeriesAirsDays.  # noqa: E501
        :type sunday: bool
        """

        self._sunday = sunday

    @property
    def thursday(self):
        """Gets the thursday of this SeriesAirsDays.  # noqa: E501


        :return: The thursday of this SeriesAirsDays.  # noqa: E501
        :rtype: bool
        """
        return self._thursday

    @thursday.setter
    def thursday(self, thursday):
        """Sets the thursday of this SeriesAirsDays.


        :param thursday: The thursday of this SeriesAirsDays.  # noqa: E501
        :type thursday: bool
        """

        self._thursday = thursday

    @property
    def tuesday(self):
        """Gets the tuesday of this SeriesAirsDays.  # noqa: E501


        :return: The tuesday of this SeriesAirsDays.  # noqa: E501
        :rtype: bool
        """
        return self._tuesday

    @tuesday.setter
    def tuesday(self, tuesday):
        """Sets the tuesday of this SeriesAirsDays.


        :param tuesday: The tuesday of this SeriesAirsDays.  # noqa: E501
        :type tuesday: bool
        """

        self._tuesday = tuesday

    @property
    def wednesday(self):
        """Gets the wednesday of this SeriesAirsDays.  # noqa: E501


        :return: The wednesday of this SeriesAirsDays.  # noqa: E501
        :rtype: bool
        """
        return self._wednesday

    @wednesday.setter
    def wednesday(self, wednesday):
        """Sets the wednesday of this SeriesAirsDays.


        :param wednesday: The wednesday of this SeriesAirsDays.  # noqa: E501
        :type wednesday: bool
        """

        self._wednesday = wednesday

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = inspect.getargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SeriesAirsDays):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, SeriesAirsDays):
            return True

        return self.to_dict() != other.to_dict()
