# coding: utf-8

"""
    TVDB API V4

    Documentation of the TVDB API V4  # noqa: E501

    The version of the OpenAPI document: 4.3.0
    Generated by: https://openapi-generator.tech
"""


import inspect
import pprint
import re  # noqa: F401
import six

from openapi_client.configuration import Configuration


class SeriesExtendedRecord(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'abbreviation': 'str',
        'airs_days': 'SeriesAirsDays',
        'airs_time': 'str',
        'aliases': 'list[Alias]',
        'artworks': 'list[ArtworkBaseRecord]',
        'characters': 'list[Character]',
        'country': 'str',
        'default_season_type': 'int',
        'first_aired': 'str',
        'lists': 'list[ListBaseRecord]',
        'genres': 'list[GenreBaseRecord]',
        'id': 'int',
        'image': 'str',
        'is_order_randomized': 'bool',
        'last_aired': 'str',
        'name': 'str',
        'name_translations': 'list[str]',
        'networks': 'list[NetworkBaseRecord]',
        'next_aired': 'str',
        'original_country': 'str',
        'original_language': 'str',
        'original_network': 'NetworkBaseRecord',
        'overview_translations': 'list[str]',
        'remote_ids': 'list[RemoteID]',
        'score': 'float',
        'seasons': 'list[SeasonBaseRecord]',
        'slug': 'str',
        'status': 'Status',
        'trailers': 'list[Trailer]'
    }

    attribute_map = {
        'abbreviation': 'abbreviation',
        'airs_days': 'airsDays',
        'airs_time': 'airsTime',
        'aliases': 'aliases',
        'artworks': 'artworks',
        'characters': 'characters',
        'country': 'country',
        'default_season_type': 'defaultSeasonType',
        'first_aired': 'firstAired',
        'lists': 'lists',
        'genres': 'genres',
        'id': 'id',
        'image': 'image',
        'is_order_randomized': 'isOrderRandomized',
        'last_aired': 'lastAired',
        'name': 'name',
        'name_translations': 'nameTranslations',
        'networks': 'networks',
        'next_aired': 'nextAired',
        'original_country': 'originalCountry',
        'original_language': 'originalLanguage',
        'original_network': 'originalNetwork',
        'overview_translations': 'overviewTranslations',
        'remote_ids': 'remoteIds',
        'score': 'score',
        'seasons': 'seasons',
        'slug': 'slug',
        'status': 'status',
        'trailers': 'trailers'
    }

    def __init__(self, abbreviation=None, airs_days=None, airs_time=None, aliases=None, artworks=None, characters=None, country=None, default_season_type=None, first_aired=None, lists=None, genres=None, id=None, image=None, is_order_randomized=None, last_aired=None, name=None, name_translations=None, networks=None, next_aired=None, original_country=None, original_language=None, original_network=None, overview_translations=None, remote_ids=None, score=None, seasons=None, slug=None, status=None, trailers=None, local_vars_configuration=None):  # noqa: E501
        """SeriesExtendedRecord - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._abbreviation = None
        self._airs_days = None
        self._airs_time = None
        self._aliases = None
        self._artworks = None
        self._characters = None
        self._country = None
        self._default_season_type = None
        self._first_aired = None
        self._lists = None
        self._genres = None
        self._id = None
        self._image = None
        self._is_order_randomized = None
        self._last_aired = None
        self._name = None
        self._name_translations = None
        self._networks = None
        self._next_aired = None
        self._original_country = None
        self._original_language = None
        self._original_network = None
        self._overview_translations = None
        self._remote_ids = None
        self._score = None
        self._seasons = None
        self._slug = None
        self._status = None
        self._trailers = None
        self.discriminator = None

        if abbreviation is not None:
            self.abbreviation = abbreviation
        if airs_days is not None:
            self.airs_days = airs_days
        if airs_time is not None:
            self.airs_time = airs_time
        if aliases is not None:
            self.aliases = aliases
        if artworks is not None:
            self.artworks = artworks
        if characters is not None:
            self.characters = characters
        if country is not None:
            self.country = country
        if default_season_type is not None:
            self.default_season_type = default_season_type
        if first_aired is not None:
            self.first_aired = first_aired
        if lists is not None:
            self.lists = lists
        if genres is not None:
            self.genres = genres
        if id is not None:
            self.id = id
        if image is not None:
            self.image = image
        if is_order_randomized is not None:
            self.is_order_randomized = is_order_randomized
        if last_aired is not None:
            self.last_aired = last_aired
        if name is not None:
            self.name = name
        if name_translations is not None:
            self.name_translations = name_translations
        if networks is not None:
            self.networks = networks
        if next_aired is not None:
            self.next_aired = next_aired
        if original_country is not None:
            self.original_country = original_country
        if original_language is not None:
            self.original_language = original_language
        if original_network is not None:
            self.original_network = original_network
        if overview_translations is not None:
            self.overview_translations = overview_translations
        if remote_ids is not None:
            self.remote_ids = remote_ids
        if score is not None:
            self.score = score
        if seasons is not None:
            self.seasons = seasons
        if slug is not None:
            self.slug = slug
        if status is not None:
            self.status = status
        if trailers is not None:
            self.trailers = trailers

    @property
    def abbreviation(self):
        """Gets the abbreviation of this SeriesExtendedRecord.  # noqa: E501


        :return: The abbreviation of this SeriesExtendedRecord.  # noqa: E501
        :rtype: str
        """
        return self._abbreviation

    @abbreviation.setter
    def abbreviation(self, abbreviation):
        """Sets the abbreviation of this SeriesExtendedRecord.


        :param abbreviation: The abbreviation of this SeriesExtendedRecord.  # noqa: E501
        :type abbreviation: str
        """

        self._abbreviation = abbreviation

    @property
    def airs_days(self):
        """Gets the airs_days of this SeriesExtendedRecord.  # noqa: E501


        :return: The airs_days of this SeriesExtendedRecord.  # noqa: E501
        :rtype: SeriesAirsDays
        """
        return self._airs_days

    @airs_days.setter
    def airs_days(self, airs_days):
        """Sets the airs_days of this SeriesExtendedRecord.


        :param airs_days: The airs_days of this SeriesExtendedRecord.  # noqa: E501
        :type airs_days: SeriesAirsDays
        """

        self._airs_days = airs_days

    @property
    def airs_time(self):
        """Gets the airs_time of this SeriesExtendedRecord.  # noqa: E501


        :return: The airs_time of this SeriesExtendedRecord.  # noqa: E501
        :rtype: str
        """
        return self._airs_time

    @airs_time.setter
    def airs_time(self, airs_time):
        """Sets the airs_time of this SeriesExtendedRecord.


        :param airs_time: The airs_time of this SeriesExtendedRecord.  # noqa: E501
        :type airs_time: str
        """

        self._airs_time = airs_time

    @property
    def aliases(self):
        """Gets the aliases of this SeriesExtendedRecord.  # noqa: E501


        :return: The aliases of this SeriesExtendedRecord.  # noqa: E501
        :rtype: list[Alias]
        """
        return self._aliases

    @aliases.setter
    def aliases(self, aliases):
        """Sets the aliases of this SeriesExtendedRecord.


        :param aliases: The aliases of this SeriesExtendedRecord.  # noqa: E501
        :type aliases: list[Alias]
        """

        self._aliases = aliases

    @property
    def artworks(self):
        """Gets the artworks of this SeriesExtendedRecord.  # noqa: E501


        :return: The artworks of this SeriesExtendedRecord.  # noqa: E501
        :rtype: list[ArtworkBaseRecord]
        """
        return self._artworks

    @artworks.setter
    def artworks(self, artworks):
        """Sets the artworks of this SeriesExtendedRecord.


        :param artworks: The artworks of this SeriesExtendedRecord.  # noqa: E501
        :type artworks: list[ArtworkBaseRecord]
        """

        self._artworks = artworks

    @property
    def characters(self):
        """Gets the characters of this SeriesExtendedRecord.  # noqa: E501


        :return: The characters of this SeriesExtendedRecord.  # noqa: E501
        :rtype: list[Character]
        """
        return self._characters

    @characters.setter
    def characters(self, characters):
        """Sets the characters of this SeriesExtendedRecord.


        :param characters: The characters of this SeriesExtendedRecord.  # noqa: E501
        :type characters: list[Character]
        """

        self._characters = characters

    @property
    def country(self):
        """Gets the country of this SeriesExtendedRecord.  # noqa: E501


        :return: The country of this SeriesExtendedRecord.  # noqa: E501
        :rtype: str
        """
        return self._country

    @country.setter
    def country(self, country):
        """Sets the country of this SeriesExtendedRecord.


        :param country: The country of this SeriesExtendedRecord.  # noqa: E501
        :type country: str
        """

        self._country = country

    @property
    def default_season_type(self):
        """Gets the default_season_type of this SeriesExtendedRecord.  # noqa: E501


        :return: The default_season_type of this SeriesExtendedRecord.  # noqa: E501
        :rtype: int
        """
        return self._default_season_type

    @default_season_type.setter
    def default_season_type(self, default_season_type):
        """Sets the default_season_type of this SeriesExtendedRecord.


        :param default_season_type: The default_season_type of this SeriesExtendedRecord.  # noqa: E501
        :type default_season_type: int
        """

        self._default_season_type = default_season_type

    @property
    def first_aired(self):
        """Gets the first_aired of this SeriesExtendedRecord.  # noqa: E501


        :return: The first_aired of this SeriesExtendedRecord.  # noqa: E501
        :rtype: str
        """
        return self._first_aired

    @first_aired.setter
    def first_aired(self, first_aired):
        """Sets the first_aired of this SeriesExtendedRecord.


        :param first_aired: The first_aired of this SeriesExtendedRecord.  # noqa: E501
        :type first_aired: str
        """

        self._first_aired = first_aired

    @property
    def lists(self):
        """Gets the lists of this SeriesExtendedRecord.  # noqa: E501


        :return: The lists of this SeriesExtendedRecord.  # noqa: E501
        :rtype: list[ListBaseRecord]
        """
        return self._lists

    @lists.setter
    def lists(self, lists):
        """Sets the lists of this SeriesExtendedRecord.


        :param lists: The lists of this SeriesExtendedRecord.  # noqa: E501
        :type lists: list[ListBaseRecord]
        """

        self._lists = lists

    @property
    def genres(self):
        """Gets the genres of this SeriesExtendedRecord.  # noqa: E501


        :return: The genres of this SeriesExtendedRecord.  # noqa: E501
        :rtype: list[GenreBaseRecord]
        """
        return self._genres

    @genres.setter
    def genres(self, genres):
        """Sets the genres of this SeriesExtendedRecord.


        :param genres: The genres of this SeriesExtendedRecord.  # noqa: E501
        :type genres: list[GenreBaseRecord]
        """

        self._genres = genres

    @property
    def id(self):
        """Gets the id of this SeriesExtendedRecord.  # noqa: E501


        :return: The id of this SeriesExtendedRecord.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this SeriesExtendedRecord.


        :param id: The id of this SeriesExtendedRecord.  # noqa: E501
        :type id: int
        """

        self._id = id

    @property
    def image(self):
        """Gets the image of this SeriesExtendedRecord.  # noqa: E501


        :return: The image of this SeriesExtendedRecord.  # noqa: E501
        :rtype: str
        """
        return self._image

    @image.setter
    def image(self, image):
        """Sets the image of this SeriesExtendedRecord.


        :param image: The image of this SeriesExtendedRecord.  # noqa: E501
        :type image: str
        """

        self._image = image

    @property
    def is_order_randomized(self):
        """Gets the is_order_randomized of this SeriesExtendedRecord.  # noqa: E501


        :return: The is_order_randomized of this SeriesExtendedRecord.  # noqa: E501
        :rtype: bool
        """
        return self._is_order_randomized

    @is_order_randomized.setter
    def is_order_randomized(self, is_order_randomized):
        """Sets the is_order_randomized of this SeriesExtendedRecord.


        :param is_order_randomized: The is_order_randomized of this SeriesExtendedRecord.  # noqa: E501
        :type is_order_randomized: bool
        """

        self._is_order_randomized = is_order_randomized

    @property
    def last_aired(self):
        """Gets the last_aired of this SeriesExtendedRecord.  # noqa: E501


        :return: The last_aired of this SeriesExtendedRecord.  # noqa: E501
        :rtype: str
        """
        return self._last_aired

    @last_aired.setter
    def last_aired(self, last_aired):
        """Sets the last_aired of this SeriesExtendedRecord.


        :param last_aired: The last_aired of this SeriesExtendedRecord.  # noqa: E501
        :type last_aired: str
        """

        self._last_aired = last_aired

    @property
    def name(self):
        """Gets the name of this SeriesExtendedRecord.  # noqa: E501


        :return: The name of this SeriesExtendedRecord.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this SeriesExtendedRecord.


        :param name: The name of this SeriesExtendedRecord.  # noqa: E501
        :type name: str
        """

        self._name = name

    @property
    def name_translations(self):
        """Gets the name_translations of this SeriesExtendedRecord.  # noqa: E501


        :return: The name_translations of this SeriesExtendedRecord.  # noqa: E501
        :rtype: list[str]
        """
        return self._name_translations

    @name_translations.setter
    def name_translations(self, name_translations):
        """Sets the name_translations of this SeriesExtendedRecord.


        :param name_translations: The name_translations of this SeriesExtendedRecord.  # noqa: E501
        :type name_translations: list[str]
        """

        self._name_translations = name_translations

    @property
    def networks(self):
        """Gets the networks of this SeriesExtendedRecord.  # noqa: E501


        :return: The networks of this SeriesExtendedRecord.  # noqa: E501
        :rtype: list[NetworkBaseRecord]
        """
        return self._networks

    @networks.setter
    def networks(self, networks):
        """Sets the networks of this SeriesExtendedRecord.


        :param networks: The networks of this SeriesExtendedRecord.  # noqa: E501
        :type networks: list[NetworkBaseRecord]
        """

        self._networks = networks

    @property
    def next_aired(self):
        """Gets the next_aired of this SeriesExtendedRecord.  # noqa: E501


        :return: The next_aired of this SeriesExtendedRecord.  # noqa: E501
        :rtype: str
        """
        return self._next_aired

    @next_aired.setter
    def next_aired(self, next_aired):
        """Sets the next_aired of this SeriesExtendedRecord.


        :param next_aired: The next_aired of this SeriesExtendedRecord.  # noqa: E501
        :type next_aired: str
        """

        self._next_aired = next_aired

    @property
    def original_country(self):
        """Gets the original_country of this SeriesExtendedRecord.  # noqa: E501


        :return: The original_country of this SeriesExtendedRecord.  # noqa: E501
        :rtype: str
        """
        return self._original_country

    @original_country.setter
    def original_country(self, original_country):
        """Sets the original_country of this SeriesExtendedRecord.


        :param original_country: The original_country of this SeriesExtendedRecord.  # noqa: E501
        :type original_country: str
        """

        self._original_country = original_country

    @property
    def original_language(self):
        """Gets the original_language of this SeriesExtendedRecord.  # noqa: E501


        :return: The original_language of this SeriesExtendedRecord.  # noqa: E501
        :rtype: str
        """
        return self._original_language

    @original_language.setter
    def original_language(self, original_language):
        """Sets the original_language of this SeriesExtendedRecord.


        :param original_language: The original_language of this SeriesExtendedRecord.  # noqa: E501
        :type original_language: str
        """

        self._original_language = original_language

    @property
    def original_network(self):
        """Gets the original_network of this SeriesExtendedRecord.  # noqa: E501


        :return: The original_network of this SeriesExtendedRecord.  # noqa: E501
        :rtype: NetworkBaseRecord
        """
        return self._original_network

    @original_network.setter
    def original_network(self, original_network):
        """Sets the original_network of this SeriesExtendedRecord.


        :param original_network: The original_network of this SeriesExtendedRecord.  # noqa: E501
        :type original_network: NetworkBaseRecord
        """

        self._original_network = original_network

    @property
    def overview_translations(self):
        """Gets the overview_translations of this SeriesExtendedRecord.  # noqa: E501


        :return: The overview_translations of this SeriesExtendedRecord.  # noqa: E501
        :rtype: list[str]
        """
        return self._overview_translations

    @overview_translations.setter
    def overview_translations(self, overview_translations):
        """Sets the overview_translations of this SeriesExtendedRecord.


        :param overview_translations: The overview_translations of this SeriesExtendedRecord.  # noqa: E501
        :type overview_translations: list[str]
        """

        self._overview_translations = overview_translations

    @property
    def remote_ids(self):
        """Gets the remote_ids of this SeriesExtendedRecord.  # noqa: E501


        :return: The remote_ids of this SeriesExtendedRecord.  # noqa: E501
        :rtype: list[RemoteID]
        """
        return self._remote_ids

    @remote_ids.setter
    def remote_ids(self, remote_ids):
        """Sets the remote_ids of this SeriesExtendedRecord.


        :param remote_ids: The remote_ids of this SeriesExtendedRecord.  # noqa: E501
        :type remote_ids: list[RemoteID]
        """

        self._remote_ids = remote_ids

    @property
    def score(self):
        """Gets the score of this SeriesExtendedRecord.  # noqa: E501


        :return: The score of this SeriesExtendedRecord.  # noqa: E501
        :rtype: float
        """
        return self._score

    @score.setter
    def score(self, score):
        """Sets the score of this SeriesExtendedRecord.


        :param score: The score of this SeriesExtendedRecord.  # noqa: E501
        :type score: float
        """

        self._score = score

    @property
    def seasons(self):
        """Gets the seasons of this SeriesExtendedRecord.  # noqa: E501


        :return: The seasons of this SeriesExtendedRecord.  # noqa: E501
        :rtype: list[SeasonBaseRecord]
        """
        return self._seasons

    @seasons.setter
    def seasons(self, seasons):
        """Sets the seasons of this SeriesExtendedRecord.


        :param seasons: The seasons of this SeriesExtendedRecord.  # noqa: E501
        :type seasons: list[SeasonBaseRecord]
        """

        self._seasons = seasons

    @property
    def slug(self):
        """Gets the slug of this SeriesExtendedRecord.  # noqa: E501


        :return: The slug of this SeriesExtendedRecord.  # noqa: E501
        :rtype: str
        """
        return self._slug

    @slug.setter
    def slug(self, slug):
        """Sets the slug of this SeriesExtendedRecord.


        :param slug: The slug of this SeriesExtendedRecord.  # noqa: E501
        :type slug: str
        """

        self._slug = slug

    @property
    def status(self):
        """Gets the status of this SeriesExtendedRecord.  # noqa: E501


        :return: The status of this SeriesExtendedRecord.  # noqa: E501
        :rtype: Status
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this SeriesExtendedRecord.


        :param status: The status of this SeriesExtendedRecord.  # noqa: E501
        :type status: Status
        """

        self._status = status

    @property
    def trailers(self):
        """Gets the trailers of this SeriesExtendedRecord.  # noqa: E501


        :return: The trailers of this SeriesExtendedRecord.  # noqa: E501
        :rtype: list[Trailer]
        """
        return self._trailers

    @trailers.setter
    def trailers(self, trailers):
        """Sets the trailers of this SeriesExtendedRecord.


        :param trailers: The trailers of this SeriesExtendedRecord.  # noqa: E501
        :type trailers: list[Trailer]
        """

        self._trailers = trailers

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = inspect.getargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SeriesExtendedRecord):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, SeriesExtendedRecord):
            return True

        return self.to_dict() != other.to_dict()
