# coding: utf-8

"""
    TVDB API V4

    Documentation of the TVDB API V4  # noqa: E501

    The version of the OpenAPI document: 4.3.0
    Generated by: https://openapi-generator.tech
"""


import inspect
import pprint
import re  # noqa: F401
import six

from openapi_client.configuration import Configuration


class Status(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'int',
        'keep_updated': 'bool',
        'name': 'str',
        'record_type': 'str'
    }

    attribute_map = {
        'id': 'id',
        'keep_updated': 'keepUpdated',
        'name': 'name',
        'record_type': 'recordType'
    }

    def __init__(self, id=None, keep_updated=None, name=None, record_type=None, local_vars_configuration=None):  # noqa: E501
        """Status - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._id = None
        self._keep_updated = None
        self._name = None
        self._record_type = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if keep_updated is not None:
            self.keep_updated = keep_updated
        if name is not None:
            self.name = name
        if record_type is not None:
            self.record_type = record_type

    @property
    def id(self):
        """Gets the id of this Status.  # noqa: E501


        :return: The id of this Status.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Status.


        :param id: The id of this Status.  # noqa: E501
        :type id: int
        """

        self._id = id

    @property
    def keep_updated(self):
        """Gets the keep_updated of this Status.  # noqa: E501


        :return: The keep_updated of this Status.  # noqa: E501
        :rtype: bool
        """
        return self._keep_updated

    @keep_updated.setter
    def keep_updated(self, keep_updated):
        """Sets the keep_updated of this Status.


        :param keep_updated: The keep_updated of this Status.  # noqa: E501
        :type keep_updated: bool
        """

        self._keep_updated = keep_updated

    @property
    def name(self):
        """Gets the name of this Status.  # noqa: E501


        :return: The name of this Status.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Status.


        :param name: The name of this Status.  # noqa: E501
        :type name: str
        """

        self._name = name

    @property
    def record_type(self):
        """Gets the record_type of this Status.  # noqa: E501


        :return: The record_type of this Status.  # noqa: E501
        :rtype: str
        """
        return self._record_type

    @record_type.setter
    def record_type(self, record_type):
        """Sets the record_type of this Status.


        :param record_type: The record_type of this Status.  # noqa: E501
        :type record_type: str
        """

        self._record_type = record_type

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = inspect.getargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Status):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Status):
            return True

        return self.to_dict() != other.to_dict()
