# coding: utf-8

"""
    TVDB API V4

    Documentation of the TVDB API V4  # noqa: E501

    The version of the OpenAPI document: 4.3.0
    Generated by: https://openapi-generator.tech
"""


import inspect
import pprint
import re  # noqa: F401
import six

from openapi_client.configuration import Configuration


class TagOptionEntity(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'name': 'str',
        'tag_name': 'str',
        'tag_id': 'int'
    }

    attribute_map = {
        'name': 'name',
        'tag_name': 'tagName',
        'tag_id': 'tagId'
    }

    def __init__(self, name=None, tag_name=None, tag_id=None, local_vars_configuration=None):  # noqa: E501
        """TagOptionEntity - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._name = None
        self._tag_name = None
        self._tag_id = None
        self.discriminator = None

        if name is not None:
            self.name = name
        if tag_name is not None:
            self.tag_name = tag_name
        if tag_id is not None:
            self.tag_id = tag_id

    @property
    def name(self):
        """Gets the name of this TagOptionEntity.  # noqa: E501


        :return: The name of this TagOptionEntity.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this TagOptionEntity.


        :param name: The name of this TagOptionEntity.  # noqa: E501
        :type name: str
        """

        self._name = name

    @property
    def tag_name(self):
        """Gets the tag_name of this TagOptionEntity.  # noqa: E501


        :return: The tag_name of this TagOptionEntity.  # noqa: E501
        :rtype: str
        """
        return self._tag_name

    @tag_name.setter
    def tag_name(self, tag_name):
        """Sets the tag_name of this TagOptionEntity.


        :param tag_name: The tag_name of this TagOptionEntity.  # noqa: E501
        :type tag_name: str
        """

        self._tag_name = tag_name

    @property
    def tag_id(self):
        """Gets the tag_id of this TagOptionEntity.  # noqa: E501


        :return: The tag_id of this TagOptionEntity.  # noqa: E501
        :rtype: int
        """
        return self._tag_id

    @tag_id.setter
    def tag_id(self, tag_id):
        """Sets the tag_id of this TagOptionEntity.


        :param tag_id: The tag_id of this TagOptionEntity.  # noqa: E501
        :type tag_id: int
        """

        self._tag_id = tag_id

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = inspect.getargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TagOptionEntity):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, TagOptionEntity):
            return True

        return self.to_dict() != other.to_dict()
