# coding: utf-8

"""
    TVDB API V4

    Documentation of the TVDB API V4  # noqa: E501

    The version of the OpenAPI document: 4.3.0
    Generated by: https://openapi-generator.tech
"""


import inspect
import pprint
import re  # noqa: F401
import six

from openapi_client.configuration import Configuration


class Translation(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'aliases': 'list[str]',
        'is_alias': 'bool',
        'is_primary': 'bool',
        'language': 'str',
        'name': 'str',
        'overview': 'str'
    }

    attribute_map = {
        'aliases': 'aliases',
        'is_alias': 'isAlias',
        'is_primary': 'isPrimary',
        'language': 'language',
        'name': 'name',
        'overview': 'overview'
    }

    def __init__(self, aliases=None, is_alias=None, is_primary=None, language=None, name=None, overview=None, local_vars_configuration=None):  # noqa: E501
        """Translation - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._aliases = None
        self._is_alias = None
        self._is_primary = None
        self._language = None
        self._name = None
        self._overview = None
        self.discriminator = None

        if aliases is not None:
            self.aliases = aliases
        if is_alias is not None:
            self.is_alias = is_alias
        if is_primary is not None:
            self.is_primary = is_primary
        if language is not None:
            self.language = language
        if name is not None:
            self.name = name
        if overview is not None:
            self.overview = overview

    @property
    def aliases(self):
        """Gets the aliases of this Translation.  # noqa: E501


        :return: The aliases of this Translation.  # noqa: E501
        :rtype: list[str]
        """
        return self._aliases

    @aliases.setter
    def aliases(self, aliases):
        """Sets the aliases of this Translation.


        :param aliases: The aliases of this Translation.  # noqa: E501
        :type aliases: list[str]
        """

        self._aliases = aliases

    @property
    def is_alias(self):
        """Gets the is_alias of this Translation.  # noqa: E501


        :return: The is_alias of this Translation.  # noqa: E501
        :rtype: bool
        """
        return self._is_alias

    @is_alias.setter
    def is_alias(self, is_alias):
        """Sets the is_alias of this Translation.


        :param is_alias: The is_alias of this Translation.  # noqa: E501
        :type is_alias: bool
        """

        self._is_alias = is_alias

    @property
    def is_primary(self):
        """Gets the is_primary of this Translation.  # noqa: E501


        :return: The is_primary of this Translation.  # noqa: E501
        :rtype: bool
        """
        return self._is_primary

    @is_primary.setter
    def is_primary(self, is_primary):
        """Sets the is_primary of this Translation.


        :param is_primary: The is_primary of this Translation.  # noqa: E501
        :type is_primary: bool
        """

        self._is_primary = is_primary

    @property
    def language(self):
        """Gets the language of this Translation.  # noqa: E501


        :return: The language of this Translation.  # noqa: E501
        :rtype: str
        """
        return self._language

    @language.setter
    def language(self, language):
        """Sets the language of this Translation.


        :param language: The language of this Translation.  # noqa: E501
        :type language: str
        """

        self._language = language

    @property
    def name(self):
        """Gets the name of this Translation.  # noqa: E501


        :return: The name of this Translation.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Translation.


        :param name: The name of this Translation.  # noqa: E501
        :type name: str
        """

        self._name = name

    @property
    def overview(self):
        """Gets the overview of this Translation.  # noqa: E501


        :return: The overview of this Translation.  # noqa: E501
        :rtype: str
        """
        return self._overview

    @overview.setter
    def overview(self, overview):
        """Sets the overview of this Translation.


        :param overview: The overview of this Translation.  # noqa: E501
        :type overview: str
        """

        self._overview = overview

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = inspect.getargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Translation):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Translation):
            return True

        return self.to_dict() != other.to_dict()
