"""
    TVDB API V4

    Documentation of the TVDB API V4  # noqa: E501

    The version of the OpenAPI document: 4.3.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.genre_base_record import GenreBaseRecord
globals()['GenreBaseRecord'] = GenreBaseRecord
from openapi_client.model.inline_response20021 import InlineResponse20021


class TestInlineResponse20021(unittest.TestCase):
    """InlineResponse20021 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20021(self):
        """Test InlineResponse20021"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse20021()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
