"""
    TVDB API V4

    Documentation of the TVDB API V4  # noqa: E501

    The version of the OpenAPI document: 4.3.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.series_statuses_api import SeriesStatusesApi  # noqa: E501


class TestSeriesStatusesApi(unittest.TestCase):
    """SeriesStatusesApi unit test stubs"""

    def setUp(self):
        self.api = SeriesStatusesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_all_series_statuses(self):
        """Test case for get_all_series_statuses

        """
        pass


if __name__ == '__main__':
    unittest.main()
