"""
    TVDB API V4

    Documentation of the TVDB API V4  # noqa: E501

    The version of the OpenAPI document: 4.3.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.movie_extended_record import MovieExtendedRecord
globals()['MovieExtendedRecord'] = MovieExtendedRecord
from openapi_client.model.inline_response20030 import InlineResponse20030


class TestInlineResponse20030(unittest.TestCase):
    """InlineResponse20030 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20030(self):
        """Test InlineResponse20030"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse20030()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
