"""
    TVDB API V4

    Documentation of the TVDB API V4  # noqa: E501

    The version of the OpenAPI document: 4.3.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.people_extended_record import PeopleExtendedRecord
globals()['PeopleExtendedRecord'] = PeopleExtendedRecord
from openapi_client.model.inline_response20033 import InlineResponse20033


class TestInlineResponse20033(unittest.TestCase):
    """InlineResponse20033 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20033(self):
        """Test InlineResponse20033"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse20033()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
