"""
    TVDB API V4

    Documentation of the TVDB API V4  # noqa: E501

    The version of the OpenAPI document: 4.3.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.character import Character
from openapi_client.model.episode_base_record import EpisodeBaseRecord
from openapi_client.model.movie_base_record import MovieBaseRecord
from openapi_client.model.series_base_record import SeriesBaseRecord
globals()['Character'] = Character
globals()['EpisodeBaseRecord'] = EpisodeBaseRecord
globals()['MovieBaseRecord'] = MovieBaseRecord
globals()['SeriesBaseRecord'] = SeriesBaseRecord
from openapi_client.model.award_nominee_base_record import AwardNomineeBaseRecord


class TestAwardNomineeBaseRecord(unittest.TestCase):
    """AwardNomineeBaseRecord unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAwardNomineeBaseRecord(self):
        """Test AwardNomineeBaseRecord"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AwardNomineeBaseRecord()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
