"""
    TVDB API V4

    Documentation of the TVDB API V4  # noqa: E501

    The version of the OpenAPI document: 4.3.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.episode_base_record import EpisodeBaseRecord
from openapi_client.model.series_extended_record import SeriesExtendedRecord
globals()['EpisodeBaseRecord'] = EpisodeBaseRecord
globals()['SeriesExtendedRecord'] = SeriesExtendedRecord
from openapi_client.model.inline_response20041_data import InlineResponse20041Data


class TestInlineResponse20041Data(unittest.TestCase):
    """InlineResponse20041Data unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20041Data(self):
        """Test InlineResponse20041Data"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse20041Data()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
