"""
    TVDB API V4

    Documentation of the TVDB API V4  # noqa: E501

    The version of the OpenAPI document: 4.3.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.network_base_record import NetworkBaseRecord


class TestNetworkBaseRecord(unittest.TestCase):
    """NetworkBaseRecord unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNetworkBaseRecord(self):
        """Test NetworkBaseRecord"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NetworkBaseRecord()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
