"""
    TVDB API V4

    Documentation of the TVDB API V4  # noqa: E501

    The version of the OpenAPI document: 4.3.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.inline_response20041_data import InlineResponse20041Data
globals()['InlineResponse20041Data'] = InlineResponse20041Data
from openapi_client.model.inline_response20041 import InlineResponse20041


class TestInlineResponse20041(unittest.TestCase):
    """InlineResponse20041 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20041(self):
        """Test InlineResponse20041"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse20041()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
