"""
    TVDB API V4

    Documentation of the TVDB API V4  # noqa: E501

    The version of the OpenAPI document: 4.3.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.studio_base_record import StudioBaseRecord


class TestStudioBaseRecord(unittest.TestCase):
    """StudioBaseRecord unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStudioBaseRecord(self):
        """Test StudioBaseRecord"""
        # FIXME: construct object with mandatory attributes with example values
        # model = StudioBaseRecord()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
