"""
    TVDB API V4

    Documentation of the TVDB API V4  # noqa: E501

    The version of the OpenAPI document: 4.3.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.source_types_api import SourceTypesApi  # noqa: E501


class TestSourceTypesApi(unittest.TestCase):
    """SourceTypesApi unit test stubs"""

    def setUp(self):
        self.api = SourceTypesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_all_source_types(self):
        """Test case for get_all_source_types

        """
        pass


if __name__ == '__main__':
    unittest.main()
