"""
    TVDB API V4

    Documentation of the TVDB API V4  # noqa: E501

    The version of the OpenAPI document: 4.3.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.gender import Gender
globals()['Gender'] = Gender
from openapi_client.model.inline_response20019 import InlineResponse20019


class TestInlineResponse20019(unittest.TestCase):
    """InlineResponse20019 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20019(self):
        """Test InlineResponse20019"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse20019()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
