"""
    TVDB API V4

    Documentation of the TVDB API V4  # noqa: E501

    The version of the OpenAPI document: 4.3.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.series_extended_record import SeriesExtendedRecord
globals()['SeriesExtendedRecord'] = SeriesExtendedRecord
from openapi_client.model.inline_response20040 import InlineResponse20040


class TestInlineResponse20040(unittest.TestCase):
    """InlineResponse20040 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20040(self):
        """Test InlineResponse20040"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse20040()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
