"""
    TVDB API V4

    Documentation of the TVDB API V4  # noqa: E501

    The version of the OpenAPI document: 4.3.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.episode_base_record import EpisodeBaseRecord
globals()['EpisodeBaseRecord'] = EpisodeBaseRecord
from openapi_client.model.inline_response20017 import InlineResponse20017


class TestInlineResponse20017(unittest.TestCase):
    """InlineResponse20017 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20017(self):
        """Test InlineResponse20017"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse20017()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
