"""
    TVDB API V4

    Documentation of the TVDB API V4  # noqa: E501

    The version of the OpenAPI document: 4.3.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.company import Company
globals()['Company'] = Company
from openapi_client.model.inline_response20013 import InlineResponse20013


class TestInlineResponse20013(unittest.TestCase):
    """InlineResponse20013 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20013(self):
        """Test InlineResponse20013"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse20013()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
