"""
    TVDB API V4

    Documentation of the TVDB API V4  # noqa: E501

    The version of the OpenAPI document: 4.3.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.award_base_record import AwardBaseRecord
from openapi_client.model.character import Character
from openapi_client.model.content_rating import ContentRating
from openapi_client.model.network_base_record import NetworkBaseRecord
from openapi_client.model.remote_id import RemoteID
from openapi_client.model.season_base_record import SeasonBaseRecord
from openapi_client.model.tag_option import TagOption
from openapi_client.model.trailer import Trailer
globals()['AwardBaseRecord'] = AwardBaseRecord
globals()['Character'] = Character
globals()['ContentRating'] = ContentRating
globals()['NetworkBaseRecord'] = NetworkBaseRecord
globals()['RemoteID'] = RemoteID
globals()['SeasonBaseRecord'] = SeasonBaseRecord
globals()['TagOption'] = TagOption
globals()['Trailer'] = Trailer
from openapi_client.model.episode_extended_record import EpisodeExtendedRecord


class TestEpisodeExtendedRecord(unittest.TestCase):
    """EpisodeExtendedRecord unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEpisodeExtendedRecord(self):
        """Test EpisodeExtendedRecord"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EpisodeExtendedRecord()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
