"""
    TVDB API V4

    Documentation of the TVDB API V4  # noqa: E501

    The version of the OpenAPI document: 4.3.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.artwork_types_api import ArtworkTypesApi  # noqa: E501


class TestArtworkTypesApi(unittest.TestCase):
    """ArtworkTypesApi unit test stubs"""

    def setUp(self):
        self.api = ArtworkTypesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_all_artwork_types(self):
        """Test case for get_all_artwork_types

        """
        pass


if __name__ == '__main__':
    unittest.main()
