"""
    TVDB API V4

    Documentation of the TVDB API V4  # noqa: E501

    The version of the OpenAPI document: 4.3.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.artwork_base_record import ArtworkBaseRecord
from openapi_client.model.episode_base_record import EpisodeBaseRecord
from openapi_client.model.trailer import Trailer
globals()['ArtworkBaseRecord'] = ArtworkBaseRecord
globals()['EpisodeBaseRecord'] = EpisodeBaseRecord
globals()['Trailer'] = Trailer
from openapi_client.model.season_extended_record import SeasonExtendedRecord


class TestSeasonExtendedRecord(unittest.TestCase):
    """SeasonExtendedRecord unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSeasonExtendedRecord(self):
        """Test SeasonExtendedRecord"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SeasonExtendedRecord()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
