"""
    TVDB API V4

    Documentation of the TVDB API V4  # noqa: E501

    The version of the OpenAPI document: 4.3.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.languages_api import LanguagesApi  # noqa: E501


class TestLanguagesApi(unittest.TestCase):
    """LanguagesApi unit test stubs"""

    def setUp(self):
        self.api = LanguagesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_all_languages(self):
        """Test case for get_all_languages

        """
        pass


if __name__ == '__main__':
    unittest.main()
