"""
    TVDB API V4

    Documentation of the TVDB API V4  # noqa: E501

    The version of the OpenAPI document: 4.3.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.source_type import SourceType
globals()['SourceType'] = SourceType
from openapi_client.model.inline_response20042 import InlineResponse20042


class TestInlineResponse20042(unittest.TestCase):
    """InlineResponse20042 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20042(self):
        """Test InlineResponse20042"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse20042()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
