"""
    TVDB API V4

    Documentation of the TVDB API V4  # noqa: E501

    The version of the OpenAPI document: 4.3.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.alias import Alias
globals()['Alias'] = Alias
from openapi_client.model.list_base_record import ListBaseRecord


class TestListBaseRecord(unittest.TestCase):
    """ListBaseRecord unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testListBaseRecord(self):
        """Test ListBaseRecord"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ListBaseRecord()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
