"""
    TVDB API V4

    Documentation of the TVDB API V4  # noqa: E501

    The version of the OpenAPI document: 4.3.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.genres_api import GenresApi  # noqa: E501


class TestGenresApi(unittest.TestCase):
    """GenresApi unit test stubs"""

    def setUp(self):
        self.api = GenresApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_all_genres(self):
        """Test case for get_all_genres

        """
        pass

    def test_get_genre_base(self):
        """Test case for get_genre_base

        """
        pass


if __name__ == '__main__':
    unittest.main()
