"""
    TVDB API V4

    Documentation of the TVDB API V4  # noqa: E501

    The version of the OpenAPI document: 4.3.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.award_base_record import AwardBaseRecord


class TestAwardBaseRecord(unittest.TestCase):
    """AwardBaseRecord unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAwardBaseRecord(self):
        """Test AwardBaseRecord"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AwardBaseRecord()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
