"""
    TVDB API V4

    Documentation of the TVDB API V4  # noqa: E501

    The version of the OpenAPI document: 4.3.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.seasons_api import SeasonsApi  # noqa: E501


class TestSeasonsApi(unittest.TestCase):
    """SeasonsApi unit test stubs"""

    def setUp(self):
        self.api = SeasonsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_season_base(self):
        """Test case for get_season_base

        """
        pass

    def test_get_season_extended(self):
        """Test case for get_season_extended

        """
        pass

    def test_get_season_translation(self):
        """Test case for get_season_translation

        """
        pass

    def test_get_season_types(self):
        """Test case for get_season_types

        """
        pass


if __name__ == '__main__':
    unittest.main()
