"""
    TVDB API V4

    Documentation of the TVDB API V4  # noqa: E501

    The version of the OpenAPI document: 4.3.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.entity_update import EntityUpdate
globals()['EntityUpdate'] = EntityUpdate
from openapi_client.model.inline_response20043 import InlineResponse20043


class TestInlineResponse20043(unittest.TestCase):
    """InlineResponse20043 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20043(self):
        """Test InlineResponse20043"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse20043()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
