"""
    TVDB API V4

    Documentation of the TVDB API V4  # noqa: E501

    The version of the OpenAPI document: 4.3.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.alias import Alias
from openapi_client.model.status import Status
globals()['Alias'] = Alias
globals()['Status'] = Status
from openapi_client.model.movie_base_record import MovieBaseRecord


class TestMovieBaseRecord(unittest.TestCase):
    """MovieBaseRecord unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMovieBaseRecord(self):
        """Test MovieBaseRecord"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MovieBaseRecord()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
