"""
    TVDB API V4

    Documentation of the TVDB API V4  # noqa: E501

    The version of the OpenAPI document: 4.3.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.search_result import SearchResult
globals()['SearchResult'] = SearchResult
from openapi_client.model.inline_response20034 import InlineResponse20034


class TestInlineResponse20034(unittest.TestCase):
    """InlineResponse20034 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20034(self):
        """Test InlineResponse20034"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse20034()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
