"""
    TVDB API V4

    Documentation of the TVDB API V4  # noqa: E501

    The version of the OpenAPI document: 4.3.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.list_base_record import ListBaseRecord
globals()['ListBaseRecord'] = ListBaseRecord
from openapi_client.model.inline_response20023 import InlineResponse20023


class TestInlineResponse20023(unittest.TestCase):
    """InlineResponse20023 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20023(self):
        """Test InlineResponse20023"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse20023()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
