"""
    TVDB API V4

    Documentation of the TVDB API V4  # noqa: E501

    The version of the OpenAPI document: 4.3.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.season_extended_record import SeasonExtendedRecord
globals()['SeasonExtendedRecord'] = SeasonExtendedRecord
from openapi_client.model.inline_response20036 import InlineResponse20036


class TestInlineResponse20036(unittest.TestCase):
    """InlineResponse20036 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20036(self):
        """Test InlineResponse20036"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse20036()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
