"""
    TVDB API V4

    Documentation of the TVDB API V4  # noqa: E501

    The version of the OpenAPI document: 4.3.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.tag_option_entity import TagOptionEntity


class TestTagOptionEntity(unittest.TestCase):
    """TagOptionEntity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTagOptionEntity(self):
        """Test TagOptionEntity"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TagOptionEntity()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
