"""
    TVDB API V4

    Documentation of the TVDB API V4  # noqa: E501

    The version of the OpenAPI document: 4.3.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.translation import Translation


class TestTranslation(unittest.TestCase):
    """Translation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTranslation(self):
        """Test Translation"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Translation()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
