"""
    TVDB API V4

    Documentation of the TVDB API V4  # noqa: E501

    The version of the OpenAPI document: 4.3.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.search_api import SearchApi  # noqa: E501


class TestSearchApi(unittest.TestCase):
    """SearchApi unit test stubs"""

    def setUp(self):
        self.api = SearchApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_search_results(self):
        """Test case for get_search_results

        """
        pass


if __name__ == '__main__':
    unittest.main()
