"""
    TVDB API V4

    Documentation of the TVDB API V4  # noqa: E501

    The version of the OpenAPI document: 4.3.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.inline_response20026_data import InlineResponse20026Data


class TestInlineResponse20026Data(unittest.TestCase):
    """InlineResponse20026Data unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20026Data(self):
        """Test InlineResponse20026Data"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse20026Data()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
