"""
    TVDB API V4

    Documentation of the TVDB API V4  # noqa: E501

    The version of the OpenAPI document: 4.3.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.awards_api import AwardsApi  # noqa: E501


class TestAwardsApi(unittest.TestCase):
    """AwardsApi unit test stubs"""

    def setUp(self):
        self.api = AwardsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_all_awards(self):
        """Test case for get_all_awards

        """
        pass

    def test_get_award(self):
        """Test case for get_award

        """
        pass

    def test_get_award_extended(self):
        """Test case for get_award_extended

        """
        pass


if __name__ == '__main__':
    unittest.main()
