"""
    TVDB API V4

    Documentation of the TVDB API V4  # noqa: E501

    The version of the OpenAPI document: 4.3.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.list_extended_record import ListExtendedRecord
globals()['ListExtendedRecord'] = ListExtendedRecord
from openapi_client.model.inline_response20025 import InlineResponse20025


class TestInlineResponse20025(unittest.TestCase):
    """InlineResponse20025 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20025(self):
        """Test InlineResponse20025"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse20025()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
