"""
    TVDB API V4

    Documentation of the TVDB API V4  # noqa: E501

    The version of the OpenAPI document: 4.3.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.award_base_record import AwardBaseRecord
from openapi_client.model.award_nominee_base_record import AwardNomineeBaseRecord
globals()['AwardBaseRecord'] = AwardBaseRecord
globals()['AwardNomineeBaseRecord'] = AwardNomineeBaseRecord
from openapi_client.model.award_category_extended_record import AwardCategoryExtendedRecord


class TestAwardCategoryExtendedRecord(unittest.TestCase):
    """AwardCategoryExtendedRecord unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAwardCategoryExtendedRecord(self):
        """Test AwardCategoryExtendedRecord"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AwardCategoryExtendedRecord()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
