"""
    TVDB API V4

    Documentation of the TVDB API V4  # noqa: E501

    The version of the OpenAPI document: 4.3.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.language import Language
globals()['Language'] = Language
from openapi_client.model.inline_response20022 import InlineResponse20022


class TestInlineResponse20022(unittest.TestCase):
    """InlineResponse20022 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20022(self):
        """Test InlineResponse20022"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse20022()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
