"""
    TVDB API V4

    Documentation of the TVDB API V4  # noqa: E501

    The version of the OpenAPI document: 4.3.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.movies_api import MoviesApi  # noqa: E501


class TestMoviesApi(unittest.TestCase):
    """MoviesApi unit test stubs"""

    def setUp(self):
        self.api = MoviesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_all_movie(self):
        """Test case for get_all_movie

        """
        pass

    def test_get_movie_base(self):
        """Test case for get_movie_base

        """
        pass

    def test_get_movie_extended(self):
        """Test case for get_movie_extended

        """
        pass

    def test_get_movie_translation(self):
        """Test case for get_movie_translation

        """
        pass


if __name__ == '__main__':
    unittest.main()
