"""
    TVDB API V4

    Documentation of the TVDB API V4  # noqa: E501

    The version of the OpenAPI document: 4.3.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.artwork_type import ArtworkType


class TestArtworkType(unittest.TestCase):
    """ArtworkType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testArtworkType(self):
        """Test ArtworkType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ArtworkType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
