"""
    TVDB API V4

    Documentation of the TVDB API V4  # noqa: E501

    The version of the OpenAPI document: 4.3.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.companies_api import CompaniesApi  # noqa: E501


class TestCompaniesApi(unittest.TestCase):
    """CompaniesApi unit test stubs"""

    def setUp(self):
        self.api = CompaniesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_all_companies(self):
        """Test case for get_all_companies

        """
        pass

    def test_get_company(self):
        """Test case for get_company

        """
        pass

    def test_get_company_types(self):
        """Test case for get_company_types

        """
        pass


if __name__ == '__main__':
    unittest.main()
