"""
    TVDB API V4

    Documentation of the TVDB API V4  # noqa: E501

    The version of the OpenAPI document: 4.3.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.movie_base_record import MovieBaseRecord
globals()['MovieBaseRecord'] = MovieBaseRecord
from openapi_client.model.inline_response20028 import InlineResponse20028


class TestInlineResponse20028(unittest.TestCase):
    """InlineResponse20028 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20028(self):
        """Test InlineResponse20028"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse20028()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
