"""
    TVDB API V4

    Documentation of the TVDB API V4  # noqa: E501

    The version of the OpenAPI document: 4.3.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.award_extended_record import AwardExtendedRecord
globals()['AwardExtendedRecord'] = AwardExtendedRecord
from openapi_client.model.inline_response2009 import InlineResponse2009


class TestInlineResponse2009(unittest.TestCase):
    """InlineResponse2009 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2009(self):
        """Test InlineResponse2009"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse2009()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
