"""
    TVDB API V4

    Documentation of the TVDB API V4  # noqa: E501

    The version of the OpenAPI document: 4.3.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.alias import Alias
from openapi_client.model.artwork_base_record import ArtworkBaseRecord
from openapi_client.model.character import Character
from openapi_client.model.genre_base_record import GenreBaseRecord
from openapi_client.model.list_base_record import ListBaseRecord
from openapi_client.model.network_base_record import NetworkBaseRecord
from openapi_client.model.remote_id import RemoteID
from openapi_client.model.season_base_record import SeasonBaseRecord
from openapi_client.model.series_airs_days import SeriesAirsDays
from openapi_client.model.status import Status
from openapi_client.model.trailer import Trailer
globals()['Alias'] = Alias
globals()['ArtworkBaseRecord'] = ArtworkBaseRecord
globals()['Character'] = Character
globals()['GenreBaseRecord'] = GenreBaseRecord
globals()['ListBaseRecord'] = ListBaseRecord
globals()['NetworkBaseRecord'] = NetworkBaseRecord
globals()['RemoteID'] = RemoteID
globals()['SeasonBaseRecord'] = SeasonBaseRecord
globals()['SeriesAirsDays'] = SeriesAirsDays
globals()['Status'] = Status
globals()['Trailer'] = Trailer
from openapi_client.model.series_extended_record import SeriesExtendedRecord


class TestSeriesExtendedRecord(unittest.TestCase):
    """SeriesExtendedRecord unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSeriesExtendedRecord(self):
        """Test SeriesExtendedRecord"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SeriesExtendedRecord()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
