"""
    TVDB API V4

    Documentation of the TVDB API V4  # noqa: E501

    The version of the OpenAPI document: 4.3.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.award_category_base_record import AwardCategoryBaseRecord
globals()['AwardCategoryBaseRecord'] = AwardCategoryBaseRecord
from openapi_client.model.award_extended_record import AwardExtendedRecord


class TestAwardExtendedRecord(unittest.TestCase):
    """AwardExtendedRecord unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAwardExtendedRecord(self):
        """Test AwardExtendedRecord"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AwardExtendedRecord()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
