# coding: utf-8

"""
    TVDB API V4

    Documentation of the TVDB API V4  # noqa: E501

    The version of the OpenAPI document: 4.3.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.inline_response20017 import InlineResponse20017  # noqa: E501
from openapi_client.rest import ApiException

class TestInlineResponse20017(unittest.TestCase):
    """InlineResponse20017 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test InlineResponse20017
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.inline_response20017.InlineResponse20017()  # noqa: E501
        if include_optional :
            return InlineResponse20017(
                data = openapi_client.models.episode_base_record.EpisodeBaseRecord(
                    aired = '', 
                    id = 56, 
                    image = '', 
                    image_type = 56, 
                    is_movie = 56, 
                    name = '', 
                    name_translations = [
                        ''
                        ], 
                    number = 56, 
                    overview_translations = [
                        ''
                        ], 
                    runtime = 56, 
                    season_number = 56, 
                    seasons = [
                        openapi_client.models.season_base_record.SeasonBaseRecord(
                            abbreviation = '', 
                            country = '', 
                            id = 56, 
                            image = '', 
                            image_type = 56, 
                            name = '', 
                            number = 56, 
                            series_id = 56, 
                            slug = '', 
                            type = 56, )
                        ], 
                    series_id = 56, ), 
                status = ''
            )
        else :
            return InlineResponse20017(
        )

    def testInlineResponse20017(self):
        """Test InlineResponse20017"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
