# coding: utf-8

"""
    TVDB API V4

    Documentation of the TVDB API V4  # noqa: E501

    The version of the OpenAPI document: 4.3.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.tag_option import TagOption  # noqa: E501
from openapi_client.rest import ApiException

class TestTagOption(unittest.TestCase):
    """TagOption unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test TagOption
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.tag_option.TagOption()  # noqa: E501
        if include_optional :
            return TagOption(
                help_text = '', 
                id = 56, 
                name = '', 
                tag = 56, 
                tag_name = ''
            )
        else :
            return TagOption(
        )

    def testTagOption(self):
        """Test TagOption"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
