# coding: utf-8

"""
    TVDB API V4

    Documentation of the TVDB API V4  # noqa: E501

    The version of the OpenAPI document: 4.3.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.entity_types_api import EntityTypesApi  # noqa: E501
from openapi_client.rest import ApiException


class TestEntityTypesApi(unittest.TestCase):
    """EntityTypesApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.entity_types_api.EntityTypesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_entity_types(self):
        """Test case for get_entity_types

        """
        pass


if __name__ == '__main__':
    unittest.main()
