# coding: utf-8

"""
    TVDB API V4

    Documentation of the TVDB API V4  # noqa: E501

    The version of the OpenAPI document: 4.3.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.list_extended_record import ListExtendedRecord  # noqa: E501
from openapi_client.rest import ApiException

class TestListExtendedRecord(unittest.TestCase):
    """ListExtendedRecord unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ListExtendedRecord
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.list_extended_record.ListExtendedRecord()  # noqa: E501
        if include_optional :
            return ListExtendedRecord(
                aliases = [
                    openapi_client.models.alias.Alias(
                        language = '', 
                        name = '', )
                    ], 
                entities = [
                    openapi_client.models.entity.Entity(
                        movie_id = 56, 
                        order = 56, 
                        series_id = 56, )
                    ], 
                id = 56, 
                is_official = True, 
                name = '', 
                name_translations = [
                    ''
                    ], 
                overview = '', 
                overview_translations = [
                    ''
                    ], 
                score = 56, 
                url = ''
            )
        else :
            return ListExtendedRecord(
        )

    def testListExtendedRecord(self):
        """Test ListExtendedRecord"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
