# coding: utf-8

"""
    TVDB API V4

    Documentation of the TVDB API V4  # noqa: E501

    The version of the OpenAPI document: 4.3.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.company import Company  # noqa: E501
from openapi_client.rest import ApiException

class TestCompany(unittest.TestCase):
    """Company unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Company
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.company.Company()  # noqa: E501
        if include_optional :
            return Company(
                active_date = '', 
                aliases = [
                    openapi_client.models.alias.Alias(
                        language = '', 
                        name = '', )
                    ], 
                country = '', 
                id = 56, 
                inactive_date = '', 
                name = '', 
                name_translations = [
                    ''
                    ], 
                overview_translations = [
                    ''
                    ], 
                primary_company_type = 56, 
                slug = ''
            )
        else :
            return Company(
        )

    def testCompany(self):
        """Test Company"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
