# coding: utf-8

"""
    TVDB API V4

    Documentation of the TVDB API V4  # noqa: E501

    The version of the OpenAPI document: 4.3.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.characters_api import CharactersApi  # noqa: E501
from openapi_client.rest import ApiException


class TestCharactersApi(unittest.TestCase):
    """CharactersApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.characters_api.CharactersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_character_base(self):
        """Test case for get_character_base

        """
        pass


if __name__ == '__main__':
    unittest.main()
