# coding: utf-8

"""
    TVDB API V4

    Documentation of the TVDB API V4  # noqa: E501

    The version of the OpenAPI document: 4.3.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.series_api import SeriesApi  # noqa: E501
from openapi_client.rest import ApiException


class TestSeriesApi(unittest.TestCase):
    """SeriesApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.series_api.SeriesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_all_series(self):
        """Test case for get_all_series

        """
        pass

    def test_get_series_base(self):
        """Test case for get_series_base

        """
        pass

    def test_get_series_episodes(self):
        """Test case for get_series_episodes

        """
        pass

    def test_get_series_extended(self):
        """Test case for get_series_extended

        """
        pass

    def test_get_series_translation(self):
        """Test case for get_series_translation

        """
        pass


if __name__ == '__main__':
    unittest.main()
