# coding: utf-8

"""
    TVDB API V4

    Documentation of the TVDB API V4  # noqa: E501

    The version of the OpenAPI document: 4.3.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.award_nominee_base_record import AwardNomineeBaseRecord  # noqa: E501
from openapi_client.rest import ApiException

class TestAwardNomineeBaseRecord(unittest.TestCase):
    """AwardNomineeBaseRecord unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test AwardNomineeBaseRecord
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.award_nominee_base_record.AwardNomineeBaseRecord()  # noqa: E501
        if include_optional :
            return AwardNomineeBaseRecord(
                character = openapi_client.models.character.Character(
                    aliases = [
                        openapi_client.models.alias.Alias(
                            language = '', 
                            name = '', )
                        ], 
                    episode_id = 56, 
                    id = 56, 
                    image = '', 
                    is_featured = True, 
                    movie_id = 56, 
                    name = '', 
                    name_translations = [
                        ''
                        ], 
                    overview_translations = [
                        ''
                        ], 
                    people_id = 56, 
                    series_id = 56, 
                    sort = 56, 
                    type = 56, 
                    url = '', ), 
                details = '', 
                episode = openapi_client.models.episode_base_record.EpisodeBaseRecord(
                    aired = '', 
                    id = 56, 
                    image = '', 
                    image_type = 56, 
                    is_movie = 56, 
                    name = '', 
                    name_translations = [
                        ''
                        ], 
                    number = 56, 
                    overview_translations = [
                        ''
                        ], 
                    runtime = 56, 
                    season_number = 56, 
                    seasons = [
                        openapi_client.models.season_base_record.SeasonBaseRecord(
                            abbreviation = '', 
                            country = '', 
                            id = 56, 
                            image = '', 
                            image_type = 56, 
                            name = '', 
                            number = 56, 
                            series_id = 56, 
                            slug = '', 
                            type = 56, )
                        ], 
                    series_id = 56, ), 
                id = 56, 
                is_winner = True, 
                movie = openapi_client.models.movie_base_record.MovieBaseRecord(
                    aliases = [
                        openapi_client.models.alias.Alias(
                            language = '', 
                            name = '', )
                        ], 
                    id = 56, 
                    image = '', 
                    name = '', 
                    name_translations = [
                        ''
                        ], 
                    overview_translations = [
                        ''
                        ], 
                    score = 1.337, 
                    slug = '', 
                    status = openapi_client.models.status.Status(
                        id = 56, 
                        keep_updated = True, 
                        name = '', 
                        record_type = '', ), ), 
                series = openapi_client.models.series_base_record.SeriesBaseRecord(
                    abbreviation = '', 
                    aliases = [
                        openapi_client.models.alias.Alias(
                            language = '', 
                            name = '', )
                        ], 
                    country = '', 
                    default_season_type = 56, 
                    first_aired = '', 
                    id = 56, 
                    image = '', 
                    is_order_randomized = True, 
                    last_aired = '', 
                    name = '', 
                    name_translations = [
                        ''
                        ], 
                    next_aired = '', 
                    original_country = '', 
                    original_language = '', 
                    original_network = openapi_client.models.network_base_record.NetworkBaseRecord(
                        abbreviation = '', 
                        country = '', 
                        id = 56, 
                        name = '', 
                        slug = '', ), 
                    overview_translations = [
                        ''
                        ], 
                    score = 1.337, 
                    slug = '', 
                    status = openapi_client.models.status.Status(
                        id = 56, 
                        keep_updated = True, 
                        name = '', 
                        record_type = '', ), ), 
                year = ''
            )
        else :
            return AwardNomineeBaseRecord(
        )

    def testAwardNomineeBaseRecord(self):
        """Test AwardNomineeBaseRecord"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
