# coding: utf-8

"""
    TVDB API V4

    Documentation of the TVDB API V4  # noqa: E501

    The version of the OpenAPI document: 4.3.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.trailer import Trailer  # noqa: E501
from openapi_client.rest import ApiException

class TestTrailer(unittest.TestCase):
    """Trailer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Trailer
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.trailer.Trailer()  # noqa: E501
        if include_optional :
            return Trailer(
                id = 56, 
                language = '', 
                name = '', 
                url = ''
            )
        else :
            return Trailer(
        )

    def testTrailer(self):
        """Test Trailer"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
