# coding: utf-8

"""
    TVDB API V4

    Documentation of the TVDB API V4  # noqa: E501

    The version of the OpenAPI document: 4.3.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.inline_response20010 import InlineResponse20010  # noqa: E501
from openapi_client.rest import ApiException

class TestInlineResponse20010(unittest.TestCase):
    """InlineResponse20010 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test InlineResponse20010
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.inline_response20010.InlineResponse20010()  # noqa: E501
        if include_optional :
            return InlineResponse20010(
                data = openapi_client.models.character.Character(
                    aliases = [
                        openapi_client.models.alias.Alias(
                            language = '', 
                            name = '', )
                        ], 
                    episode_id = 56, 
                    id = 56, 
                    image = '', 
                    is_featured = True, 
                    movie_id = 56, 
                    name = '', 
                    name_translations = [
                        ''
                        ], 
                    overview_translations = [
                        ''
                        ], 
                    people_id = 56, 
                    series_id = 56, 
                    sort = 56, 
                    type = 56, 
                    url = '', ), 
                status = ''
            )
        else :
            return InlineResponse20010(
        )

    def testInlineResponse20010(self):
        """Test InlineResponse20010"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
