# coding: utf-8

"""
    TVDB API V4

    Documentation of the TVDB API V4  # noqa: E501

    The version of the OpenAPI document: 4.3.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.people_extended_record import PeopleExtendedRecord  # noqa: E501
from openapi_client.rest import ApiException

class TestPeopleExtendedRecord(unittest.TestCase):
    """PeopleExtendedRecord unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test PeopleExtendedRecord
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.people_extended_record.PeopleExtendedRecord()  # noqa: E501
        if include_optional :
            return PeopleExtendedRecord(
                aliases = [
                    openapi_client.models.alias.Alias(
                        language = '', 
                        name = '', )
                    ], 
                awards = [
                    openapi_client.models.award_base_record.AwardBaseRecord(
                        id = 56, 
                        name = '', )
                    ], 
                biographies = [
                    openapi_client.models.biography.Biography(
                        biography = '', 
                        language = '', )
                    ], 
                birth = '', 
                birth_place = '', 
                characters = [
                    openapi_client.models.character.Character(
                        aliases = [
                            openapi_client.models.alias.Alias(
                                language = '', 
                                name = '', )
                            ], 
                        episode_id = 56, 
                        id = 56, 
                        image = '', 
                        is_featured = True, 
                        movie_id = 56, 
                        name = '', 
                        name_translations = [
                            ''
                            ], 
                        overview_translations = [
                            ''
                            ], 
                        people_id = 56, 
                        series_id = 56, 
                        sort = 56, 
                        type = 56, 
                        url = '', )
                    ], 
                death = '', 
                gender = 56, 
                id = 56, 
                image = '', 
                name = '', 
                races = [
                    openapi_client.models.race.Race()
                    ], 
                remote_ids = [
                    openapi_client.models.remote_id.RemoteID(
                        id = '', 
                        type = 56, )
                    ], 
                score = 56, 
                tag_options = [
                    openapi_client.models.tag_option.TagOption(
                        help_text = '', 
                        id = 56, 
                        name = '', 
                        tag = 56, 
                        tag_name = '', )
                    ]
            )
        else :
            return PeopleExtendedRecord(
        )

    def testPeopleExtendedRecord(self):
        """Test PeopleExtendedRecord"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
