# coding: utf-8

"""
    TVDB API V4

    Documentation of the TVDB API V4  # noqa: E501

    The version of the OpenAPI document: 4.3.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.lists_api import ListsApi  # noqa: E501
from openapi_client.rest import ApiException


class TestListsApi(unittest.TestCase):
    """ListsApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.lists_api.ListsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_all_lists(self):
        """Test case for get_all_lists

        """
        pass

    def test_get_list(self):
        """Test case for get_list

        """
        pass

    def test_get_list_extended(self):
        """Test case for get_list_extended

        """
        pass


if __name__ == '__main__':
    unittest.main()
