# coding: utf-8

"""
    TVDB API V4

    Documentation of the TVDB API V4  # noqa: E501

    The version of the OpenAPI document: 4.3.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.inline_response20041 import InlineResponse20041  # noqa: E501
from openapi_client.rest import ApiException

class TestInlineResponse20041(unittest.TestCase):
    """InlineResponse20041 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test InlineResponse20041
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.inline_response20041.InlineResponse20041()  # noqa: E501
        if include_optional :
            return InlineResponse20041(
                data = openapi_client.models.inline_response_200_41_data.inline_response_200_41_data(
                    series = openapi_client.models.series_extended_record.SeriesExtendedRecord(
                        abbreviation = '', 
                        airs_days = openapi_client.models.series_airs_days.SeriesAirsDays(
                            friday = True, 
                            monday = True, 
                            saturday = True, 
                            sunday = True, 
                            thursday = True, 
                            tuesday = True, 
                            wednesday = True, ), 
                        airs_time = '', 
                        aliases = [
                            openapi_client.models.alias.Alias(
                                language = '', 
                                name = '', )
                            ], 
                        artworks = [
                            openapi_client.models.artwork_base_record.ArtworkBaseRecord(
                                id = 56, 
                                image = '', 
                                language = '', 
                                score = 1.337, 
                                thumbnail = '', 
                                type = 56, )
                            ], 
                        characters = [
                            openapi_client.models.character.Character(
                                episode_id = 56, 
                                id = 56, 
                                image = '', 
                                is_featured = True, 
                                movie_id = 56, 
                                name = '', 
                                name_translations = [
                                    ''
                                    ], 
                                overview_translations = [
                                    ''
                                    ], 
                                people_id = 56, 
                                series_id = 56, 
                                sort = 56, 
                                type = 56, 
                                url = '', )
                            ], 
                        country = '', 
                        default_season_type = 56, 
                        first_aired = '', 
                        lists = [
                            openapi_client.models.list_base_record.ListBaseRecord(
                                id = 56, 
                                is_official = True, 
                                name = '', 
                                overview = '', 
                                url = '', )
                            ], 
                        genres = [
                            openapi_client.models.genre_base_record.GenreBaseRecord(
                                id = 56, 
                                name = '', 
                                slug = '', )
                            ], 
                        id = 56, 
                        image = '', 
                        is_order_randomized = True, 
                        last_aired = '', 
                        name = '', 
                        name_translations = [
                            ''
                            ], 
                        networks = [
                            openapi_client.models.network_base_record.NetworkBaseRecord(
                                abbreviation = '', 
                                country = '', 
                                id = 56, 
                                name = '', 
                                slug = '', )
                            ], 
                        next_aired = '', 
                        original_country = '', 
                        original_language = '', 
                        original_network = openapi_client.models.network_base_record.NetworkBaseRecord(
                            abbreviation = '', 
                            country = '', 
                            id = 56, 
                            name = '', 
                            slug = '', ), 
                        overview_translations = [
                            ''
                            ], 
                        remote_ids = [
                            openapi_client.models.remote_id.RemoteID(
                                id = '', 
                                type = 56, )
                            ], 
                        score = 1.337, 
                        seasons = [
                            openapi_client.models.season_base_record.SeasonBaseRecord(
                                abbreviation = '', 
                                country = '', 
                                id = 56, 
                                image = '', 
                                image_type = 56, 
                                name = '', 
                                number = 56, 
                                series_id = 56, 
                                slug = '', 
                                type = 56, )
                            ], 
                        slug = '', 
                        status = openapi_client.models.status.Status(
                            id = 56, 
                            keep_updated = True, 
                            name = '', 
                            record_type = '', ), 
                        trailers = [
                            openapi_client.models.trailer.Trailer(
                                id = 56, 
                                language = '', 
                                name = '', 
                                url = '', )
                            ], ), 
                    episodes = [
                        openapi_client.models.episode_base_record.EpisodeBaseRecord(
                            aired = '', 
                            id = 56, 
                            image = '', 
                            image_type = 56, 
                            is_movie = 56, 
                            name = '', 
                            number = 56, 
                            runtime = 56, 
                            season_number = 56, 
                            series_id = 56, )
                        ], ), 
                status = ''
            )
        else :
            return InlineResponse20041(
        )

    def testInlineResponse20041(self):
        """Test InlineResponse20041"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
