# coding: utf-8

"""
    TVDB API V4

    Documentation of the TVDB API V4  # noqa: E501

    The version of the OpenAPI document: 4.3.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.award_extended_record import AwardExtendedRecord  # noqa: E501
from openapi_client.rest import ApiException

class TestAwardExtendedRecord(unittest.TestCase):
    """AwardExtendedRecord unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test AwardExtendedRecord
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.award_extended_record.AwardExtendedRecord()  # noqa: E501
        if include_optional :
            return AwardExtendedRecord(
                categories = [
                    openapi_client.models.award_category_base_record.AwardCategoryBaseRecord(
                        allow_co_nominees = True, 
                        award = openapi_client.models.award_base_record.AwardBaseRecord(
                            id = 56, 
                            name = '', ), 
                        for_movies = True, 
                        for_series = True, 
                        id = 56, 
                        name = '', )
                    ], 
                id = 56, 
                name = '', 
                score = 56
            )
        else :
            return AwardExtendedRecord(
        )

    def testAwardExtendedRecord(self):
        """Test AwardExtendedRecord"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
