# coding: utf-8

"""
    TVDB API V4

    Documentation of the TVDB API V4  # noqa: E501

    The version of the OpenAPI document: 4.3.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.inline_response20018 import InlineResponse20018  # noqa: E501
from openapi_client.rest import ApiException

class TestInlineResponse20018(unittest.TestCase):
    """InlineResponse20018 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test InlineResponse20018
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.inline_response20018.InlineResponse20018()  # noqa: E501
        if include_optional :
            return InlineResponse20018(
                data = openapi_client.models.episode_extended_record.EpisodeExtendedRecord(
                    aired = '', 
                    airs_after_season = 56, 
                    airs_before_episode = 56, 
                    airs_before_season = 56, 
                    awards = [
                        openapi_client.models.award_base_record.AwardBaseRecord(
                            id = 56, 
                            name = '', )
                        ], 
                    characters = [
                        openapi_client.models.character.Character(
                            aliases = [
                                openapi_client.models.alias.Alias(
                                    language = '', 
                                    name = '', )
                                ], 
                            episode_id = 56, 
                            id = 56, 
                            image = '', 
                            is_featured = True, 
                            movie_id = 56, 
                            name = '', 
                            name_translations = [
                                ''
                                ], 
                            overview_translations = [
                                ''
                                ], 
                            people_id = 56, 
                            series_id = 56, 
                            sort = 56, 
                            type = 56, 
                            url = '', )
                        ], 
                    content_ratings = [
                        openapi_client.models.content_rating.ContentRating(
                            id = 56, 
                            name = '', 
                            country = '', 
                            content_type = '', 
                            order = 56, 
                            full_name = '', )
                        ], 
                    id = 56, 
                    image = '', 
                    image_type = 56, 
                    is_movie = 56, 
                    name = '', 
                    name_translations = [
                        ''
                        ], 
                    network = openapi_client.models.network_base_record.NetworkBaseRecord(
                        abbreviation = '', 
                        country = '', 
                        id = 56, 
                        name = '', 
                        slug = '', ), 
                    number = 56, 
                    overview_translations = [
                        ''
                        ], 
                    production_code = '', 
                    remote_ids = [
                        openapi_client.models.remote_id.RemoteID(
                            id = '', 
                            type = 56, )
                        ], 
                    runtime = 56, 
                    season_number = 56, 
                    seasons = [
                        openapi_client.models.season_base_record.SeasonBaseRecord(
                            abbreviation = '', 
                            country = '', 
                            id = 56, 
                            image = '', 
                            image_type = 56, 
                            name = '', 
                            number = 56, 
                            series_id = 56, 
                            slug = '', 
                            type = 56, )
                        ], 
                    series_id = 56, 
                    tag_options = [
                        openapi_client.models.tag_option.TagOption(
                            help_text = '', 
                            id = 56, 
                            name = '', 
                            tag = 56, 
                            tag_name = '', )
                        ], 
                    trailers = [
                        openapi_client.models.trailer.Trailer(
                            id = 56, 
                            language = '', 
                            name = '', 
                            url = '', )
                        ], ), 
                status = ''
            )
        else :
            return InlineResponse20018(
        )

    def testInlineResponse20018(self):
        """Test InlineResponse20018"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
