# coding: utf-8

"""
    TVDB API V4

    Documentation of the TVDB API V4  # noqa: E501

    The version of the OpenAPI document: 4.3.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.people_base_record import PeopleBaseRecord  # noqa: E501
from openapi_client.rest import ApiException

class TestPeopleBaseRecord(unittest.TestCase):
    """PeopleBaseRecord unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test PeopleBaseRecord
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.people_base_record.PeopleBaseRecord()  # noqa: E501
        if include_optional :
            return PeopleBaseRecord(
                aliases = [
                    openapi_client.models.alias.Alias(
                        language = '', 
                        name = '', )
                    ], 
                id = 56, 
                image = '', 
                name = '', 
                score = 56
            )
        else :
            return PeopleBaseRecord(
        )

    def testPeopleBaseRecord(self):
        """Test PeopleBaseRecord"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
