"""
    TVDB API V4

    Documentation of the TVDB API V4  # noqa: E501

    The version of the OpenAPI document: 4.3.0
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from openapi_client.model_utils import (  # noqa: F401
    ApiTypeError,
    ModelComposed,
    ModelNormal,
    ModelSimple,
    cached_property,
    change_keys_js_to_python,
    convert_js_args_to_python_args,
    date,
    datetime,
    file_type,
    none_type,
    validate_get_composed_info,
)

def lazy_import():
    from openapi_client.model.alias import Alias
    from openapi_client.model.artwork_base_record import ArtworkBaseRecord
    from openapi_client.model.award_base_record import AwardBaseRecord
    from openapi_client.model.character import Character
    from openapi_client.model.genre_base_record import GenreBaseRecord
    from openapi_client.model.list_base_record import ListBaseRecord
    from openapi_client.model.release import Release
    from openapi_client.model.remote_id import RemoteID
    from openapi_client.model.status import Status
    from openapi_client.model.studio_base_record import StudioBaseRecord
    from openapi_client.model.trailer import Trailer
    globals()['Alias'] = Alias
    globals()['ArtworkBaseRecord'] = ArtworkBaseRecord
    globals()['AwardBaseRecord'] = AwardBaseRecord
    globals()['Character'] = Character
    globals()['GenreBaseRecord'] = GenreBaseRecord
    globals()['ListBaseRecord'] = ListBaseRecord
    globals()['Release'] = Release
    globals()['RemoteID'] = RemoteID
    globals()['Status'] = Status
    globals()['StudioBaseRecord'] = StudioBaseRecord
    globals()['Trailer'] = Trailer


class MovieExtendedRecord(ModelNormal):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Attributes:
      allowed_values (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          with a capitalized key describing the allowed value and an allowed
          value. These dicts store the allowed enum values.
      attribute_map (dict): The key is attribute name
          and the value is json key in definition.
      discriminator_value_class_map (dict): A dict to go from the discriminator
          variable value to the discriminator class name.
      validations (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          that stores validations for max_length, min_length, max_items,
          min_items, exclusive_maximum, inclusive_maximum, exclusive_minimum,
          inclusive_minimum, and regex.
      additional_properties_type (tuple): A tuple of classes accepted
          as additional properties values.
    """

    allowed_values = {
    }

    validations = {
    }

    additional_properties_type = None

    _nullable = False

    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        lazy_import()
        return {
            'aliases': ([Alias],),  # noqa: E501
            'artworks': ([ArtworkBaseRecord],),  # noqa: E501
            'audio_languages': ([str],),  # noqa: E501
            'awards': ([AwardBaseRecord],),  # noqa: E501
            'box_office': (str,),  # noqa: E501
            'budget': (str,),  # noqa: E501
            'characters': ([Character],),  # noqa: E501
            'lists': ([ListBaseRecord],),  # noqa: E501
            'genres': ([GenreBaseRecord],),  # noqa: E501
            'id': (int,),  # noqa: E501
            'image': (str,),  # noqa: E501
            'name': (str,),  # noqa: E501
            'name_translations': ([str],),  # noqa: E501
            'original_country': (str,),  # noqa: E501
            'original_language': (str,),  # noqa: E501
            'overview_translations': ([str],),  # noqa: E501
            'releases': ([Release],),  # noqa: E501
            'remote_ids': ([RemoteID],),  # noqa: E501
            'score': (float,),  # noqa: E501
            'slug': (str,),  # noqa: E501
            'status': (Status,),  # noqa: E501
            'studios': ([StudioBaseRecord],),  # noqa: E501
            'subtitle_languages': ([str],),  # noqa: E501
            'trailers': ([Trailer],),  # noqa: E501
        }

    @cached_property
    def discriminator():
        return None


    attribute_map = {
        'aliases': 'aliases',  # noqa: E501
        'artworks': 'artworks',  # noqa: E501
        'audio_languages': 'audioLanguages',  # noqa: E501
        'awards': 'awards',  # noqa: E501
        'box_office': 'boxOffice',  # noqa: E501
        'budget': 'budget',  # noqa: E501
        'characters': 'characters',  # noqa: E501
        'lists': 'lists',  # noqa: E501
        'genres': 'genres',  # noqa: E501
        'id': 'id',  # noqa: E501
        'image': 'image',  # noqa: E501
        'name': 'name',  # noqa: E501
        'name_translations': 'nameTranslations',  # noqa: E501
        'original_country': 'originalCountry',  # noqa: E501
        'original_language': 'originalLanguage',  # noqa: E501
        'overview_translations': 'overviewTranslations',  # noqa: E501
        'releases': 'releases',  # noqa: E501
        'remote_ids': 'remoteIds',  # noqa: E501
        'score': 'score',  # noqa: E501
        'slug': 'slug',  # noqa: E501
        'status': 'status',  # noqa: E501
        'studios': 'studios',  # noqa: E501
        'subtitle_languages': 'subtitleLanguages',  # noqa: E501
        'trailers': 'trailers',  # noqa: E501
    }

    _composed_schemas = {}

    required_properties = set([
        '_data_store',
        '_check_type',
        '_spec_property_naming',
        '_path_to_item',
        '_configuration',
        '_visited_composed_classes',
    ])

    @convert_js_args_to_python_args
    def __init__(self, *args, **kwargs):  # noqa: E501
        """MovieExtendedRecord - a model defined in OpenAPI

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            aliases ([Alias]): [optional]  # noqa: E501
            artworks ([ArtworkBaseRecord]): [optional]  # noqa: E501
            audio_languages ([str]): [optional]  # noqa: E501
            awards ([AwardBaseRecord]): [optional]  # noqa: E501
            box_office (str): [optional]  # noqa: E501
            budget (str): [optional]  # noqa: E501
            characters ([Character]): [optional]  # noqa: E501
            lists ([ListBaseRecord]): [optional]  # noqa: E501
            genres ([GenreBaseRecord]): [optional]  # noqa: E501
            id (int): [optional]  # noqa: E501
            image (str): [optional]  # noqa: E501
            name (str): [optional]  # noqa: E501
            name_translations ([str]): [optional]  # noqa: E501
            original_country (str): [optional]  # noqa: E501
            original_language (str): [optional]  # noqa: E501
            overview_translations ([str]): [optional]  # noqa: E501
            releases ([Release]): [optional]  # noqa: E501
            remote_ids ([RemoteID]): [optional]  # noqa: E501
            score (float): [optional]  # noqa: E501
            slug (str): [optional]  # noqa: E501
            status (Status): [optional]  # noqa: E501
            studios ([StudioBaseRecord]): [optional]  # noqa: E501
            subtitle_languages ([str]): [optional]  # noqa: E501
            trailers ([Trailer]): [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
